### ISSUE TITLE
[Bug]: text not clear in dark mode

### ISSUE THREAD

**Issue by MaroB05** [QuivrHQ/quivr#1778]
### What happened?

I was trying the app in dark theme, and I noticed that the text is hardly distinguishable from the background.
![Screenshot 2023-12-01 230546](https://github.com/StanGirard/quivr/assets/72122152/049862f4-a5b3-4899-88fa-569edade0e66)

**Comment by tsensei** [comment]
@StanGirard Can you please assign me to this issue ?

**Comment by StanGirard** [comment]
Done ✅

**Comment by jaikishpai** [comment]
@StanGirard I have created a PR - #1941 with more enhancements for dark mode.

**Comment by Shailesh93602** [comment]
Hello i want to start contributing where can I help let me know
