### ISSUE TITLE
[Bug]: dependency failed to start: container supabase-analytics is unhealthy

### ISSUE THREAD

**Issue by shiliu2023** [QuivrHQ/quivr#1783]
### What happened?

dependency failed to start: container supabase-analytics is unhealthy

**Comment by shiliu2023** [comment]
when i docker compose up --build -d

**Comment by abdulkabiraliyu** [comment]
I am having the same issue on windows. Please help me

**Comment by drmetro09** [comment]
Same issue if someone can help would be thankful

**Comment by aoxiong777** [comment]
Same problem, looking forward to the solution, thanks
