### ISSUE TITLE
[Feature]: Explore Brains is nicer

### ISSUE THREAD

**Issue by StanGirard** [QuivrHQ/quivr#1788]
### The Feature

<img width="1585" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/84b0d60a-078f-4af3-862d-4a47dfc4fd27">

I'd love to allow people to be able to filter out brains, to sort them by number of people subscribed, see the number of people subscribed to each.

**Comment by bhanuteja-03** [comment]
Hi @StanGirard , I want to try this issue, please assign it to me.
