### ISSUE TITLE
[Feature]: Filter on which file to ask the question

### ISSUE THREAD

**Issue by StanGirard** [QuivrHQ/quivr#1794]
### The Feature

<img width="1187" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/b3bd3b74-30bc-4f79-95b7-d7bf817509d0">

I'd like the user to be able to filter by typing `/` the file on which he wants to ask a question

### Motivation, pitch

Allow the user to ask question on only one file :)

**Comment by sanatcodes** [comment]
Hi @StanGirard, would love to give this feature a shot. Can you please assign it to me 😄

**Comment by StanGirard** [comment]
Give it a go :)

**Comment by sanatcodes** [comment]
Hi @StanGirard, unfortunately, I haven't had a chance to work on this yet :/ 

I need more time to become familiar with the codebase. Probably will pick up another issue down the line. Don't want to block this issue for someone else who is willing and able to work on it. Thanks!

**Comment by saloni0419** [comment]
Can you please assign this issue to me @StanGirard

**Comment by Abhi1992002** [comment]
Hi @StanGirard , can i give it a try?
