### ISSUE TITLE
[Bug]: Quivr not working with ollama2

### ISSUE THREAD

**Issue by lopes221** [QuivrHQ/quivr#1850]
### What happened?

I have deployed quivr to ude Ollama.
I deployed on Kubernetes and I did a port-forward in order to have it working locally.

https://github.com/jmorganca/ollama/tree/main/examples/kubernetes

Following quivr deployment instructions, I tried first commenting the **openai Key** variable but it complains that must be set, so I left there, so the only change i have done was updating the ollama variable. http://localhost:11434
```
#### QUIVR Configuration


OPENAI_API_KEY=CHANGE-ME 
CREATE_FIRST_USER=true # set to false if you want to create the first user manually by default it will create a user with the following credentials:
# login: admin@quivr.app
# password: admin

#LOCAL
OLLAMA_API_BASE_URL=http://localhost:11434 # Uncomment to activate ollama. This is the local url for the ollama api

```

Everything is deployed, supabase, quivr and I create a brain with the ollama/ollama2 options that it's defined\ and upload a file.
The thing is when I start chat, nothing happens, seems like quivrr is not able to talk with ollama.
I tried http://localhost:11434 also tried http://127.0.0.0:11434 none of them works.

When I use the model via command line, it works, however when I use via quivr interface, I get no output from chat.

### When I deploy using open ai, it works perfectly.

Any idea?

**Comment by georgeqin96** [comment]
have the same Problem，I run ollama in Docker, How to test if the API is function. is there specific instruction like Python code?

**Comment by lopes221** [comment]
Hi @georgeqin96 I needed to reinstall my docker, I have Ubuntu 22.04.
So I removed docker desktop. https://docs.docker.com/desktop/uninstall/
Then I reinstalled docker again but just docker engine.
https://docs.docker.com/engine/install/ubuntu/
So, I assume the issue was related to permissions on my docker desktop, somehow with the file systems.
I just didn't have much time to spend troubleshooting it so I resolve this way that I mentioned.

**Comment by ricoisme** [comment]
I got the same issue too, any workaround?

**Comment by lopes221** [comment]
I am still stuck with the same issue actually @ricoisme  and @georgeqin96  if you find something, share with us here.

**Comment by georgeqin96** [comment]
Yes, I reinstall all and solved the problem. also I figure out the ollama to use the GPU and much faster. but I got new problem, the Ollama didn't talk with the docs that feeded.

**Comment by lopes221** [comment]
Yeah, @georgeqin96 that's exactly the problem I face now.
Ollama2 seems not able to talk with the documents.

**Comment by georgeqin96** [comment]
but Ollama could talk about something else like 'why the sky is blue', and Ollama would balabala a lot. It just didn't talk about anything in the Docs.

**Comment by enriqueramosg** [comment]
Ive tried reinstalling and everything but cant solve the issue. Are you in v0.0.152?? Did you change any config when installing?
