### ISSUE TITLE
[Bug]: Can not run with ollama locally

### ISSUE THREAD

**Issue by CarolineBukk** [QuivrHQ/quivr#1904]
### What happened?

I am trying to run with ollama locally. 

When I build quivr in docker and first I receive an error regarding rate limitation. Which I assume is due to not using any openai key, but I assumed I would not have too, when running it locally? I can still log in to quivr and the application keeps running so I am not sure weather or not this is a problem. 

However when I write a message to a brain it always return an empty message and I receive an error "Failed to resolve 'host.docker.internal'". I have tried to set OLLAMA_API_BASE_URL to http://host.docker.internal:11434, http://localhost:11434,  and http://127.0.0.1:11434. But I get errors for all of them. 

I am running all code on a remote computer and using the localhost pages on my local machine if that could be relevant. 

### Relevant log output

```bash
# Rate limitation error
supabase-vector                 | 2023-12-15T12:33:43.446827Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: dns error: failed to lookup address information: Try again error_type="request_failed" stage="processing" internal_log_rate_limit=true
supabase-vector                 | 2023-12-15T12:33:43.446879Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: dns error: failed to lookup address information: Try again internal_log_rate_limit=tr


# 'host.docker.internal' error
 200 OK"
backend-core                    | INFO:     172.21.0.1:59162 - "GET /chat HTTP/1.1" 200 OK
backend-core                    | 2023-12-15 12:31:48,943 [ERROR] llm.knowledge_brain_qa: Caught exception: Error raised by inference endpoint: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe316809c50>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))
backend-core                    | 2023-12-15 12:31:48,943 [ERROR] llm.knowledge_brain_qa: Error processing source documents: 'NoneType' object has no attribute 'get'
supabase-kong                   | 172.21.0.18 - - [15/Dec/2023:12:31:48 +0000] "PATCH /rest/v1/chat_history?message_id=eq.3db81a10-6b19-4b51-b1f8-faddd2f7338b HTTP/1.1" 200 261 "-" "python-httpx/0.24.1"
```

**Comment by CarolineBukk** [comment]
I tried replacing host.docker.internal to the gateway IP, but I got the same error message. I think the main problem may be that it can not find /api/embeddings for ollama, do you have any more suggestion on how to resolve this?

**Comment by kyilmaz80** [comment]
Updating to the most recent version of ollama2 should fix the problem. In my case I am using Ollama2 server remotely. After updating it, it worked for me.
