### ISSUE TITLE
[Feature]: GPT MODEL

### ISSUE THREAD

**Issue by DurgaPrasad2898** [QuivrHQ/quivr#1915]
### The Feature

We are very excited using Quivr with your exceptional features, we now want to use "**GPT-4 model**" in our setup, but in drop down of Chat configuration settings only had "**gpt-3.5 turbo-1106**" with Max tokens: 3000. Can you please help us how can we use GPT-4 model in our setup with OpenAI.

### Motivation, pitch

We are using Quivr, would like to implement **GPT-4 Model**

**Comment by DurgaPrasad2898** [comment]
We will wait for your reply ...

**Comment by Kusnezow94** [comment]
Any Updates on this? Could be great to use 128K turbo model now..
