### ISSUE TITLE
[Enhancement] Incorporate Underline for Link in Top Bar to Enhance UX

### ISSUE THREAD

**Issue by hempun10** [QuivrHQ/quivr#1944]
### The Feature

<img width="1470" alt="Screenshot 2024-01-01 at 8 53 16 PM" src="https://github.com/StanGirard/quivr/assets/106392313/531edb01-edfa-440d-bcdf-977162c3fa6b">

### Motivation, pitch

Adding a simple underline at the link can enhance the UI/UX.

**Comment by rishitabura** [comment]
I can solve this issue

**Comment by rishitabura** [comment]
@hempun10  Could you please share some video of this?

**Comment by hempun10** [comment]
@rishitabura you can refer to an image that I have attached above. The bot also has given the relevant solution.

**Comment by yisusworldwide** [comment]
@hempun10 hello, just made a PR "**#2214**" so let's see if I can solve this. Best, Jesus.
