### ISSUE TITLE
[Bug]: Not getting chat response when running Quivr on WSL local machine?

### ISSUE THREAD

**Issue by quic-khrahul** [QuivrHQ/quivr#1947]
### What happened?

I am using WSL on my windows machine to locally run the Quivr app.

I am able to successfully launch the project using below instructions:
#docker compose pull
#docker compose -f docker-compose-ollama.yml up --build 

In http://localhost:3000/chat. When I am trying to chat, the app is not responding. Am I missing something? Or this application won't work on WSL?
I am not getting any error as such.

Thanks in Advance.

**Comment by enriqueramosg** [comment]
I have the same problem. At first it worked just fine with default brain but when I created one it started to give blank responses despite the brain you asked.

**Comment by rahulkhandelwal456** [comment]
> add any openai api key even though ur not using. this worked for me.

I tried adding openai api, it is still not working. "Error: you exceeded your current quota, please check your plan and billing details". It is a new OpenAI account, But the openai key never worked.
Why it is asking for OpenAI key, If I am using llama2?

**Comment by mikestaub** [comment]
I had to modify the "Maximum Words per Response" value on this page, click save then it worked for me. http://localhost:3000/brains-management/BRAIN_ID

**Comment by rahulkhandelwal456** [comment]
> I had to modify the "Maximum Words per Response" value on this page, click save then it worked for me. http://localhost:3000/brains-management/BRAIN_ID

I tried changing "Maximum Words per Response" as well, but still I am getting blank response.

backend-core                    | 2024-01-08 07:31:38,486:INFO - HTTP Request: GET http://kong:8000/rest/v1/customers?select=email&email=eq.rahul.com "HTTP/1.1 500 Internal Server Error"
backend-core                    | 2024-01-08 07:31:38,486 [INFO] models.databases.supabase.user_usage: None
backend-core                    | 2024-01-08 07:31:38,486 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core                    | 2024-01-08 07:31:38,486 [ERROR] models.databases.supabase.user_usage: {'code': 'XX000', 'details': None, 'hint': None, 'message': 'called `Result::unwrap()` on an `Err` value: InvalidPosition'}

 Do I need to register somewhere else as well?

Thanks,
