### ISSUE TITLE
[Bug]: Dark theme not applied properly

### ISSUE THREAD

**Issue by rishitabura** [QuivrHQ/quivr#1988]
### What happened?

When i apply for dark theme , the side bar is not visible properly. 

![Screenshot 2024-01-04 223904](https://github.com/StanGirard/quivr/assets/102479434/a656d387-723f-4fac-bde1-8ac242603fe2)

**Comment by rishitabura** [comment]
I can solve this issue, please assign this to me

**Comment by StanGirard** [comment]
@rishitabura feel free to fix it :)

**Comment by harshlakhara** [comment]
I will be working on this issue.
