### ISSUE TITLE
[Bug]: Error while checking if user is a premium user

### ISSUE THREAD

**Issue by weidiguo** [QuivrHQ/quivr#1991]
### What happened?

Successful conversation, but when accessing the brain, it will report an error, the first error is 401, the second error is 404, from the backend log I see that there is a problem accessing the customers database, please how can I solve it

### Relevant log output

```bash
backend-core  | 2024-01-05 16:02:15,303:INFO - HTTP Request: GET https://easdepp.supabase.co/rest/v1/customers?select=email&email=sad@gmeil.com "HTTP/1.1 500 Internal Server Error"
backend-core  | 2024-01-05 16:02:15,304 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2024-01-05 16:02:15,304 [ERROR] models.databases.supabase.user_usage: {'code': 'XX000', 'details': None, 'hint': None, 'message': 'called `Result::unwrap()` on an `Err` value: InvalidPosition'}


Request URL:
http://tasdasdasdsa/_next/static/chunks/app/brains-management/%5BbrainId%5D/page-fab912aabeede5ef.js
Request Method:
GET
Status Code:
404 Not Found
Remote Address:


Request URL:
https://api.june.so/sdk/page
Request Method:
POST
Status Code:
401 Unauthorized

Request URL:
https://api.june.so/sdk/identify
Request Method:
POST
Status Code:
401 Unauthorized


Request URL:
http://asdsad/_vercel/insights/script.js
Request Method:
GET
Status Code:
404 Not Found
```

**Comment by StanGirard** [comment]
@weidiguo this isn't an issue that should impact your experience of Quivr. It is merely because you have not setup Stripe but isn't blocking. 

The issue is something else.

**Comment by weidiguo** [comment]
@StanGirard How do I set up Stripe, thank you

**Comment by weidiguo** [comment]
@StanGirard 
Now I don't have access to this table customers  

An error is reported when creating a brain page

Application error: a client-side exception has occurred (see the browser console for more information).
