### ISSUE TITLE
[Bug]: only llama2 allowed locally

### ISSUE THREAD

**Issue by sumitsodhi88** [QuivrHQ/quivr#1994]
### What happened?

only llama2 is supported which is not a good model compared to mistral/ mixtral.
ollama can run both of these models.

**Comment by StanGirard** [comment]
The embedding is only supported by llama2. However the questions are answered with any models you want.

**Comment by enriqueramosg** [comment]
> The embedding is only supported by llama2. However the questions are answered with any models you want.

Can you do an installation tut for ollama??
