### ISSUE TITLE
Timeout error during process of csv file of less than 1 mb

### ISSUE THREAD

**Issue by spinxdigital** [QuivrHQ/quivr#2000]
### What happened?

I uploaded csv file with more than 30 columns and 2000 rows. After processing around 100 records, it is throwing an error in console.

### Relevant log output

```bash
NFO:     127.0.0.1:40028 - "GET /healthz HTTP/1.1" 200 OK
worker        | [2024-01-09 12:11:16,239: INFO/ForkPoolWorker-8] HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
worker        | [2024-01-09 12:11:29,314: INFO/ForkPoolWorker-8] HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
backend-core  | INFO:     127.0.0.1:57230 - "GET /healthz HTTP/1.1" 200 OK
worker        | 2024-01-09 12:11:41,963 [ERROR] packages.embeddings.vectors: Error creating vector for document timed out
worker        | [2024-01-09 12:11:42,048: WARNING/ForkPoolWorker-8] Error processing file: 'NoneType' object is not iterable
```

**Comment by spinxdigital** [comment]
Attaching sample file with data.
[sample.csv](https://github.com/StanGirard/quivr/files/13873908/sample.csv)

**Comment by permanzh** [comment]
same problem:
`worker        | 2024-01-09 14:29:30,739 [ERROR] packages.embeddings.vectors: Error creating vector for document Error raised by inference API HTTP code: 504, <html>
worker        | <head><title>504 Gateway Time-out</title></head>
worker        | <body>
worker        | <center><h1>504 Gateway Time-out</h1></center>
worker        | <hr><center>nginx/1.20.1</center>
worker        | </body>
worker        | </html>
worker        |
worker        | [2024-01-09 14:29:30,751: WARNING/ForkPoolWorker-1] Error processing file: 'NoneType' object is not iterable`
