### ISSUE TITLE
supabase start - unexpected EOF - At statement 0: create extension if not exists "vector" with schema "public"

### ISSUE THREAD

**Issue by No-Work-Team** [QuivrHQ/quivr#2001]
### What happened?

After I submitted the "supabase start" command I get the following messages:
/Quivr$ supabase start
Skipping migration local_20240107152745_ollama.sql... (file name must match pattern "<timestamp>_name.sql")
Applying migration 20240103173626_init.sql...
unexpected EOF
At statement 0: create extension if not exists "vector" with schema "public"

**Comment by phoenix19792013** [comment]
i have the same issue

root@wass-Standard-PC-i440FX-PIIX-1996:~/Quivr# supabase start
Skipping migration local_20240107152745_ollama.sql... (file name must match pattern "<timestamp>_name.sql")
Applying migration 20240103173626_init.sql...
unexpected EOF                                                              
At statement 0: create extension if not exists "vector" with schema "public"
Try rerunning the command with --debug to troubleshoot the error.

**Comment by cucumbermosaic** [comment]
I have the same issue! 
when I try to manually run 20240103173626_init.sql, whole supabase terminate

**Comment by dastaj** [comment]
the same - any solutions?

**Comment by dblinick** [comment]
I will add to this thread - Did anyone manage to get it resolved?

**Comment by Braga-source** [comment]
Same problem.

Applying migration 20240103173626_init.sql...
unexpected EOF                                                              
At statement 0: create extension if not exists "vector" with schema "public"

**Comment by bioshazard** [comment]
I get this on a fresh clone. Logs report an illegal instruction:

```
$ docker logs supabase_db_secondbrain -f
...
 2024-05-11 10:05:17.049 UTC [10] LOG:  server process (PID 983) was terminated by signal 4: Illegal instruction
 2024-05-11 10:05:17.049 UTC [10] DETAIL:  Failed process was running: 
        -- source: dashboard
        -- user: self host
        -- date: 2024-05-11T10:05:16.745Z

        create extension vector
        with
          schema extensions;

 2024-05-11 10:05:17.049 UTC [10] LOG:  terminating any other active server processes
 2024-05-11 10:05:17.055 UTC [10] LOG:  all server processes terminated; reinitializing
 2024-05-11 10:05:17.124 UTC [984] LOG:  database system was interrupted; last known up at 2024-05-11 10:01:26 UTC
 ...
```

And that is the documented way to enable `pgvector` per the Supabase docs: https://supabase.com/docs/guides/database/extensions/pgvector?queryGroups=database-method&database-method=sql

**Comment by bioshazard** [comment]
Ok... so my suspicion is that "Illegal instruction" refers to the CPU instruction set being incompatible with PG Vector. I was running this on a machine that has a CPU with AVX2. That has given me trouble in the past with embedding stuff so I think everyone in this thread is running it on a CPU without AVX2. Going to try to run this on my newer machine to verify. Even old versions of supabase have this error on that machine. This can never be fixed unless you can find a way to run a version of pgvector that does not require AVX2 support. Just a theory though, but makes perfect sense if it is the case.

**Comment by bioshazard** [comment]
Yep. Confirmed. It works perfectly fine on my newer machine with AVX support. That's gotta be it. Hope this helps.

```
bios@new-machine$ cat /proc/cpuinfo  | grep -oe ...avx... | sort | uniq
i1 avx2 s
ve avx f1
```

**Comment by Niskeletor** [comment]
Hello there! as @bioshazard  said , I encountered the same issue while emulating a VM with Proxmox. My CPU was set to x86-64-v2-AES, and I received the exact same "Illegal instruction" error.

In my case, I resolved the issue by changing the CPU emulation to host. Now everything works correctly.

My processor is: 12 x Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz.

I hope this can help

**Comment by FrancescoMasaia** [comment]
Same problem with Proxmox, solved using the right cpu vendor instead of the generic one.

**Comment by piyush-saurabh** [comment]
Same issue with Ubuntu VM running on Proxmox. Changed the CPU to 'host' and it worked!

**Comment by super25k** [comment]
> Same issue with Ubuntu VM running on Proxmox. Changed the CPU to 'host' and it worked!

This worked for me too.
