### ISSUE TITLE
[Feature]:  Quivr not accessible over network

### ISSUE THREAD

**Issue by sumitsodhi88** [QuivrHQ/quivr#2002]
### What happened?

The accessing through LAN "http://***.***.*.*/3000" shows a limited version of Quivr.

**Comment by gaboh89** [comment]
Hi @oanhcuongdo, did you find a solution for your issue? I'm having the same behavior on my server

**Comment by oanhcuongdo** [comment]
> Hi @oanhcuongdo, did you find a solution for your issue? I'm having the same behavior on my server

hi i am still having that error. anyone knows how fix?
