### ISSUE TITLE
[Feature]: vscode integration extension 

### ISSUE THREAD

**Issue by RicardoGEsteves** [QuivrHQ/quivr#2005]
### The Feature

It would be awesome if you guys create an extension to integrate with vscode.

### Motivation, pitch

It made it much easier to integrate the files and their context, with a specific topic or project or even to use brains in a more agile and practical way.

### Twitter / LinkedIn details

@RicardoGEsteves https://twitter.com/ricardogesteves
@RicardoGEsteves https://www.linkedin.com/in/ricardogesteves

**Comment by Siddharth1605** [comment]
I would like to work on this feature, can anyone assign me
