### ISSUE TITLE
[Feature]: add transition effect for accordion component on home page

### ISSUE THREAD

**Issue by khareyash05** [QuivrHQ/quivr#2032]
### The Feature

![image](https://github.com/StanGirard/quivr/assets/60147732/45ba6fba-1867-4423-8f23-504bbfaf8ced)
A smooth transition will be great!!. I would like to work on this one

### Motivation, pitch

ENable better UX

**Comment by soulmini** [comment]
@michaeltansg i want to work on this issue can you assign to me
