### ISSUE TITLE
[Feature]: Increase the environment variable to override the Openai Api Base Url.

### ISSUE THREAD

**Issue by AprildreamMI** [QuivrHQ/quivr#2084]
### The Feature

ncrease the environment variable to override the Openaide Api Base Url
example:
![image](https://github.com/StanGirard/quivr/assets/31964372/31c1729b-3236-4d1a-88f4-af45c7aa3389)

### Motivation, pitch

In some regions, it is not possible to directly use OpenAI and instead private proxies are used. The API format provided by the proxy server is the same as that of OpenAI. By providing environment variables to override the API Base URL, it can help them with their usage. Thank you.

**Comment by Passerby1011** [comment]
Same issue

**Comment by smallarmy** [comment]
same issue

**Comment by LinhanXu3928** [comment]
same issue

**Comment by LinhanXu3928** [comment]
same issue

**Comment by samos123** [comment]
I need this so I can point Quivr to an OSS model that's served by vLLM. Any plans to add this directly into Quivr?

**Comment by SunshineWood** [comment]
@AprildreamMI There is a new solution now, I want to modify the openai base url
