### ISSUE TITLE
[Bug]: brains disapeared and can't create new ones

### ISSUE THREAD

**Issue by diegovelezg** [QuivrHQ/quivr#2114]
### What happened?

**Cannot get brains:**
![image](https://github.com/StanGirard/quivr/assets/28717078/e4401a99-0034-49dc-802d-35fe748d9205)

**Cannot create a new ones;**
![image](https://github.com/StanGirard/quivr/assets/28717078/c6a49829-651a-4e14-ac37-43e43e6c5625)

![image](https://github.com/StanGirard/quivr/assets/28717078/255147c0-d260-4fa2-ab37-e83cf70d69be)

- Google Chrome for linux 120.0.6099.199 (Build oficial) (64 bits)

**Comment by hilt-pravin** [comment]
![Screenshot from 2024-01-31 22-15-01](https://github.com/StanGirard/quivr/assets/152949896/0fe03ada-3ae1-4864-bbc8-6accf4940290)
![Screenshot from 2024-01-31 22-14-16](https://github.com/StanGirard/quivr/assets/152949896/0db65301-706c-433d-9e88-0649ba17ac71)

![Screenshot from 2024-01-31 22-14-53](https://github.com/StanGirard/quivr/assets/152949896/8fb80924-530f-4351-a671-b1f3bd6e25f3)



I've attached a few error screens. It appears there's an issue in the configuration. It's not fetching chat history, brains, or even the default brain, and there's an issue when creating a new brain. I've gone through the project configuration multiple times, but I'm still encountering the same errors.
