### ISSUE TITLE
[Bug]: The front-end interface is incomplete

### ISSUE THREAD

**Issue by etdown** [QuivrHQ/quivr#2126]
### What happened?

A bug happened!
![image](https://github.com/StanGirard/quivr/assets/107334275/ca26d6a3-ed51-44b6-bf37-8b8804282ab2)

![image](https://github.com/StanGirard/quivr/assets/107334275/614874f0-9da6-4648-ac55-2dc52a7db391)

### Relevant log output

```bash
认真的吗
```

**Comment by AndrewYNGI** [comment]
I'm having the same problem, it should be related to the Content Security Policy

**Comment by ichengang** [comment]
> 我遇到了同样的问题，应该与内容安全策略有关

朋友，你是否已经解决。如果是可以告诉我更详细的解决办法吗。我想我很需要

**Comment by ifeingewgewmlkm** [comment]
the instructions need an overhaul and are not matching the docs site

SORT IT OUT

**Comment by peterkanda** [comment]
Hi everyone, I am new here and a big fan. I had the same issue and this is how i resolved it. 

1.  Stop all containers running

2  update .env file
 **_"NEXT_PUBLIC_ENV=local
NEXT_PUBLIC_BACKEND_URL=http://yourdomain.com:5050
NEXT_PUBLIC_SUPABASE_URL=http://yourdomain.com:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
NEXT_PUBLIC_CMS_URL=https://cms.quivr.app
NEXT_PUBLIC_FRONTEND_URL=http://yourdomain.com:*
"_**

3. Find **next.config.js** under frontend files then add your url under - ConsentSecurityPolicy
such as 

"default-src": [
    "'self'",
    "https://fonts.googleapis.com",
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    "https://api.june.so",
    "https://us.posthog.com",
    "https://preview.quivr.app",
    "https://chat.quivr.app",
    "*.intercom.io",
    "*.intercomcdn.com",
    "https://*.octolane.com",
    "https://*.vercel.app",
    **_"www.youdomain.com",
    "http://yourdomain.com",_**
    process.env.NEXT_PUBLIC_FRONTEND_URL,
  ],

do the same for the rest **"connect-src",  "img-src",...**

5. Then run 
      **_docker compose pull 
      docker compose up_**

**Comment by turbcool** [comment]
Just set `NEXT_PUBLIC_FRONTEND_URL` with your domain in `.env` and rebuild the `frontend` container.
