### ISSUE TITLE
[Bug]: :IP:5050 

### ISSUE THREAD

**Issue by ichengang** [QuivrHQ/quivr#2127]
### What happened?

A bug happened!
When I enter the server port 5050, the front end only displays {"status":"OK"}

### Relevant log output

```bash
{"status":"OK"}
```

**Comment by ichengang** [comment]
I think I don't want 5050 as the front end, 5050 is just a port of a certain management service to facilitate management through the web page.

But I have installed quivr many times, and every time the front-end page of port 3000 is messed up, and the login port inside cannot be used.

My steps are to pull the warehouse, modify OPENAPIKEY in the .env file, and then start it through docker compose. Later, the configuration of supabase was modified in this file. But there is still no effective change in this result, depending on

**Comment by StanGirard** [comment]
Hey my friend the frontend is on port 3000. If you have issues with it please change the variable from localhost to your IP in the .env file.

**Comment by ichengang** [comment]
ok 我试一下

**Comment by ichengang** [comment]
> 嘿，我的朋友，前端位于端口 3000 上。如果您遇到问题，请将 .env 文件中的变量从 localhost 更改为您的 IP。

I like you, you can see my problem at a glance
