### ISSUE TITLE
[Bug]: README Quick Start and documentation outdated 

### ISSUE THREAD

**Issue by arya-coding** [QuivrHQ/quivr#2128]
### What happened?

Hello Quivr, 

I was initially excited to discover and try out Quivr. However, after a few days of trying to make it work locally with ollama, I realized that the README of this repository is misleading and outdated. 
- It does not specify that you have to manually create a user on Supabase. 
- It does not specific if you need to do a supabase sql migration (I have to guess here)

- Additionally, the interface seems to have a hybrid approach now, as it invite you to pay for the PRO option even when running locally. 

Furthermore, the website documentation on ollama is also incorrect :
- The file paths are not right 
- The commands specified do not work. 
**Example** :  look at this please, it's the official Quivr documentation for setting up Ollama, the command is not only useless (mv same file/folder), but also wrong as the file is in a subdirectory called migration : 
<img width="745" alt="image" src="https://github.com/StanGirard/quivr/assets/9800251/1dc66fab-3a48-49ac-b89c-1b7ee5cfa623">

- The quivr ollama docker compose somehow disappeared from the repository

This is a major issue for new users on your platform. As a result, I ended up going for another project on GitHub. 

I hope to come back to try out and promote Quivr because so far it has been a lost of time for me.

**Comment by StanGirard** [comment]
@arya-coding Thanks a lot for your feedback. 

I'm wondering which version of Quivr you have as we have updated the installation of quivr to make it very simple with Ollama. 

Did you follow the new readme ? 

I'm sorry to hear that you don't like the project. Please feel free to open a PR to help us improve this entirely open-source project.

**Comment by tinchopu** [comment]
@dosu-bot the link provided in Step 1 https://supabase.com/docs/guides/database/migrations returns a 404

**Comment by tinchopu** [comment]
Ok I made it work locally. In step 5 you need to "cd supabase" and from there run "supabase start". Then "cd .." and from there continue with "docker compose pull" ...

**Comment by 3koozy** [comment]
I can't run quiver as of today due to login and creating users on local supabase issues..
![image](https://github.com/QuivrHQ/quivr/assets/18246137/3d59e468-cf0d-46d5-b80d-7626ae2f53c3)
