### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ethercp** [QuivrHQ/quivr#2135]
### What happened?

A bug happened!
Dear warehouse developers, I don't know why the front-end interface is always incomplete after deployment. Which step was not done correctly?
![image](https://github.com/StanGirard/quivr/assets/107334275/fd945eb3-708e-4310-8f87-72a1bd8b014c)

**Comment by moslemmj** [comment]
I also have this problem and I don't know how to fix it. Can you help me?

![image](https://github.com/QuivrHQ/quivr/assets/41994843/b1067ed2-eb88-4fcc-bc6d-ca8445b53868)
