### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [QuivrHQ/quivr#2207]
### What happened?

Few serious security vulnerability has been disclosed to [huntr](https://huntr.com/) for this repo.
Fix those bug ASAP
report link -->
https://huntr.com/bounties/80f6bef0-5879-47dd-b71b-c7386e479bd3/
https://huntr.com/bounties/6baa7a7c-7b85-4ee6-a955-c26d9b74c5cc/
https://huntr.com/bounties/c9b8254f-11e9-4fb0-b1bc-b2b07f958cb6/
https://huntr.com/bounties/b6011986-954a-47da-a60c-fc7aebc8005d/
https://huntr.com/bounties/3ed6f551-93f3-470a-8abe-f003342505b1/
https://huntr.com/bounties/547d5d66-bdcc-4d21-8cb1-dc5c09cd7c47/
https://huntr.com/bounties/c692c816-6131-4827-b498-dccfec05988a/

report are currently private and only repo maintainer can see the report details.
If you are repo maintainer then there is 2 way to view the report details
   1.  by signup
   2. by secret magick link that  has been sent to your mail  by huntr.com.

**Comment by StanGirard** [comment]
Thanks a lot ! I'll check them out !
