### ISSUE TITLE
[Feature]: Increase the ability of changing  the OpenAI API Base Url.

### ISSUE THREAD

**Issue by the-lazy-me** [QuivrHQ/quivr#2213]
### The Feature

Increase the ability of changing  the OpenAI API Base Url.

### Motivation, pitch

In some regions, it is not possible to directly use OpenAI and instead private proxies are used. What's more,by changing OpenAI API Base Url,the cost of training can reduce a lot

**Comment by huliangbing** [comment]
Hope a developer will add this feature

**Comment by huliangbing** [comment]
In the .env file, add OPENAI_BASE_URL=http://*.*.*.*:xxxx/v1, and it works.

**Comment by heishen6** [comment]
> In the .env file, add OPENAI_BASE_URL=http://_._._._:xxxx/v1, and it works.在 .env 文件中添加 OPENAI_BASE_URL=http://...:xxxx/v1，它可以工作。

Is it supported now?
Or the advice you gave them?
