### ISSUE TITLE
[Bug]: Local Development Instructions dont work

### ISSUE THREAD

**Issue by ramnathv** [QuivrHQ/quivr#2237]
### What happened?

I cloned the repo and tried to get the local development setup working by running

```
docker compose -f docker-compose.dev.yml up --build
```

While I did not get any error, I noticed that no frontend ui was loaded at `localhost:3000`. Upon inspection, it seems like `docker-compose.dev` file does not contain any frontend service. It seems to have been deleted in an earlier commit.

**Comment by StanGirard** [comment]
Yes you then need to go to the frontend folder and do:

yarn
yarn run dev

have fun !
