### ISSUE TITLE
[Feature]: Is it possible to change the name of the ai models?

### ISSUE THREAD

**Issue by mooodali** [QuivrHQ/quivr#2302]
Hi guys
Is it possible to change the name of the ai models?
Let me give an example
I want whenever the user asks a question like "Can you introduce yourself" or "Hello, how are you?"
I don't want him to answer this
"I am an AI language model developed by OpenAI called GPT-3"
rather say
"My name is Jack and I am an intelligent robot"

**Comment by MeTaNoV** [comment]
you can specify a custom prompt for each brain where you can define this behavior
