### ISSUE TITLE
[Bug]: local supabase db reset ,after create a new user,Failed to create user: An error has occurred: Failed to fetch

### ISSUE THREAD

**Issue by caihexin** [QuivrHQ/quivr#2321]
### What happened?

A bug happened
![image](https://github.com/QuivrHQ/quivr/assets/13762872/cb33e76c-2d13-4f41-bd75-78e6cc101a79)

**Comment by caihexin** [comment]
![image](https://github.com/QuivrHQ/quivr/assets/13762872/75ffc4d1-91f4-4547-b573-aae7b5cb4515)
![image](https://github.com/QuivrHQ/quivr/assets/13762872/859a9be3-bc78-4ae3-8635-835ad80e1ff4)
**no change  supabase/config.toml**
but :
can not create user
![image](https://github.com/QuivrHQ/quivr/assets/13762872/18178a47-0919-4b0f-a3fa-ef307346335f)

**Comment by caihexin** [comment]
Can you  @dosu-bot. provide me with a create user SQL directly so that I can create an account to log in to Quivr ,Thank

**Comment by caihexin** [comment]
![image](https://github.com/QuivrHQ/quivr/assets/13762872/c77c39f4-18fd-44f9-916f-376a17ec57d4)
admin@quivr.app What is the password？



> Based on the structure of the "auth"."users" table in the Supabase database for Quivr, you can use the following SQL command to create a new user:
> 
> ```sql
> INSERT INTO "auth"."users" (
>     "id", 
>     "email", 
>     "encrypted_password", 
>     "created_at", 
>     "updated_at"
> ) 
> VALUES (
>     'new_user_id', 
>     'new_user_email@example.com', 
>     'encrypted_password_here', 
>     CURRENT_TIMESTAMP, 
>     CURRENT_TIMESTAMP
> );
> ```
> 
> Please replace `'new_user_id'`, `'new_user_email@example.com'`, and `'encrypted_password_here'` with your desired user ID, email, and encrypted password respectively.
> 
> Note that the `encrypted_password` should be a hashed version of the password. You can use a function like `crypt('password', gen_salt('bf'))` to generate this, replacing `'password'` with the actual password.
> 
> So the final command would look like this:
> 
> ```sql
> INSERT INTO "auth"."users" (
>     "id", 
>     "email", 
>     "encrypted_password", 
>     "created_at", 
>     "updated_at"
> ) 
> VALUES (
>     'new_user_id', 
>     'new_user_email@example.com', 
>     crypt('password', gen_salt('bf')), 
>     CURRENT_TIMESTAMP, 
>     CURRENT_TIMESTAMP
> );
> ```
> 
> Please be aware that this is a direct manipulation of the database and should be done with caution. Always ensure to backup your data before performing such operations.
> 
> For more information, you can refer to the [supabase/seed.sql](https://github.com/QuivrHQ/quivr/blob/main/supabase/seed.sql) file in the Quivr repository.
> 
> ## Sources
> * [supabase/seed.sql](https://github.com/QuivrHQ/quivr/blob/main/supabase/seed.sql)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

![image](https://github.com/QuivrHQ/quivr/assets/13762872/ba885f55-fc24-4799-a720-aac9032af0b1)
好像表结构不一样

**Comment by caihexin** [comment]
![image](https://github.com/QuivrHQ/quivr/assets/13762872/488b6613-1ae0-4415-b7c2-9c7876a15d27)
admin@quivr.app  What is the password？admin无法登录

**Comment by neozhu** [comment]
config.toml
```bash
[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://10.33.1.37" # Change your docker host IP
# OpenAI API Key to use for Supabase AI in the Supabase Studio.
openai_api_key = "env(OPENAI_API_KEY)"
```

**Comment by caihexin** [comment]
worker        | [2024-03-10 09:20:00,001: INFO/MainProcess] Task celery_worker.process_integration_brain_sync[f124eafd-6306-4efa-8ece-27457bced09a] received
worker        | [2024-03-10 09:20:00,031: INFO/ForkPoolWorker-58] HTTP Request: GET http://192.168.12.253:54321/rest/v1/integrations_user?select=%2A%2C%20integrations%20%28%29&integrations.integration_name=eq.notion "HTTP/1.1 200 OK"
worker        | [2024-03-10 09:20:00,047: ERROR/ForkPoolWorker-58] Task celery_worker.process_integration_brain_sync[f124eafd-6306-4efa-8ece-27457bced09a] raised unexpected: TypeError("'NoneType' object is not iterable")

@neozhu , studio app create user success,but quivr app cannot login .

**Comment by ddr5ecc** [comment]
I have the same issue as well. Probably something wrong with supabase...

<img width="1353" alt="Screenshot 2024-03-14 at 22 27 34" src="https://github.com/QuivrHQ/quivr/assets/78187435/f4346943-ece1-4833-ae5d-718c3efd7a79">

**Comment by xinsonggaodragonplus** [comment]
> edit config.toml in studio section change api_url.
> 
> ```shell
> [studio]
> enabled = true
> # Port to use for Supabase Studio.
> port = 54323
> # External URL of the API server that frontend connects to.
> api_url = "http://10.33.1.37" # Change your docker host IP
> # OpenAI API Key to use for Supabase AI in the Supabase Studio.
> openai_api_key = "env(OPENAI_API_KEY)"
> ```

I also encountered this problem, and I solved it in this way. Thank you very much
