### ISSUE TITLE
Cannot login at browser remotely

### ISSUE THREAD

**Issue by ddr5ecc** [QuivrHQ/quivr#2348]
### What happened?

<img width="1155" alt="Screenshot 2024-03-15 at 11 00 09" src="https://github.com/QuivrHQ/quivr/assets/78187435/1e79423e-eac5-464a-b56a-ee03e5eb962a">
<img width="1159" alt="Screenshot 2024-03-15 at 10 58 51" src="https://github.com/QuivrHQ/quivr/assets/78187435/2047fabb-95b4-454f-8c9b-c6dd0f6b0f54">

I can access the supabase and make a new account: a@a, with a simple password a.  
However, when I get into the web UI, pressing the "login" button, nothing responded at all. 

According to https://github.com/QuivrHQ/quivr/issues/2262, "supabase db reset" might work before but not work for me. 

Any suggestions? Thanks in advance.

**Comment by jerry123cao** [comment]
so am i,ressing the "login" button, nothing responded at all

**Comment by ddr5ecc** [comment]
<img width="1151" alt="Screenshot 2024-03-17 at 09 57 21" src="https://github.com/QuivrHQ/quivr/assets/78187435/a1ff3e72-3eac-4cf1-9d57-af66a43c94cf">

I found similar errors in Supabase log: Kong API, Postgres, PostgREST, Auth, Storage, Realtime. They all have errors on fetching data.

**Comment by ddr5ecc** [comment]
Here are some error messages: 

`
flower          | 2024-03-18 00:25:18,361:WARNING - Inspect method active_queues failed
flower          | 2024-03-18 00:25:18,362:WARNING - Inspect method registered failed
flower          | 2024-03-18 00:25:18,363:WARNING - Inspect method scheduled failed
flower          | 2024-03-18 00:25:18,367:WARNING - Inspect method reserved failed
flower          | 2024-03-18 00:25:18,368:WARNING - Inspect method active failed
flower          | 2024-03-18 00:25:18,386:WARNING - Inspect method revoked failed
flower          | 2024-03-18 00:25:18,392:WARNING - Inspect method stats failed
flower          | 2024-03-18 00:25:18,394:WARNING - Inspect method conf failed
worker          | [2024-03-18 00:25:18,472: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
worker          | whether broker connection retries are made during startup in Celery 6.0 and above.
worker          | If you wish to retain the existing behavior for retrying connections on startup,
worker          | you should set broker_connection_retry_on_startup to True.
worker          |   warnings.warn(
worker          |

worker          | [2024-03-18 00:25:19,658: ERROR/ForkPoolWorker-2] Task celery_worker.process_integration_brain_sync[0696d2c2-a899-4794-ad6b-3ae5086cdf19] raised unexpected: TypeError("'NoneType' object is not iterable")
worker          | Traceback (most recent call last):
worker          |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
worker          |     R = retval = fun(*args, **kwargs)
worker          |                  ^^^^^^^^^^^^^^^^^^^^
worker          |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
worker          |     return self.run(*args, **kwargs)
worker          |            ^^^^^^^^^^^^^^^^^^^^^^^^^
worker          |   File "/code/celery_worker.py", line 192, in process_integration_brain_sync
worker          |     for integration in integrations:
worker          | TypeError: 'NoneType' object is not iterable

`

**Comment by ddr5ecc** [comment]
<img width="1624" alt="Screenshot 2024-03-17 at 17 56 23" src="https://github.com/QuivrHQ/quivr/assets/78187435/aca89736-d229-4c85-960a-cee37317a312">


I got progress. 
I can login inside the container. 

1. How to make it access for local network. 
2. Solving "Type Error: Fail to Fetch"
