### ISSUE TITLE
Have multiple chats

### ISSUE THREAD

**Issue by StanGirard** [QuivrHQ/quivr#235]
#234 required first

I'd like to have multiple chats saved in my browser

<img width="1840" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/db74c685-e5a7-4edd-b898-3b051cb0a900">

Something like that

**Comment by StanGirard** [comment]
Yes it does ! 

However as this is a first good issue people can do it without the database. But yes ultimately it will be stored in db

**Comment by imakecodes** [comment]
Yeap, make sense!

**Comment by santhosh82** [comment]
@StanGirard I would like to work on this

**Comment by mamadoudicko** [comment]
@santhosh82  👍🏽

Feel free to regularly push your code without hesitation (sharing your progress and gathering small feedbacks)

You can also join our Discord community for further interaction

Enjoy it!
