### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wangshuai-wuhan** [QuivrHQ/quivr#2366]
### What happened?

A bug happened!

### Relevant log output

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/celery_worker.py", line 181, in process_integration_brain_sync_user_brain
    notion_connector.poll()
  File "/code/modules/brain/integrations/Notion/Notion_connector.py", line 357, in poll
    db_res = self._search_notion(query_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/modules/brain/integrations/Notion/Notion_connector.py", line 99, in _search_notion
    res.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.notion.com/v1/search
Clock	64
Root	<Task: celery_worker.process_integration_brain_sync(830f71d0-d755-47a7-a1b0-9c65796c7549) SUCCESS clock:60>
```

**Comment by JonWhiteRA** [comment]
Related to this:  

worker        | [2024-03-27 20:45:00,043: ERROR/ForkPoolWorker-2] Task celery_worker.process_integration_brain_sync[7998e013-f15b-4a8b-9b0c-77e724659f88] raised unexpected: ConnectError('[Errno -2] Name or service not known')
worker        | Traceback (most recent call last):
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
worker        |     yield
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
worker        |     resp = self._pool.handle_request(req)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
worker        |     raise exc from None
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
worker        |     response = connection.handle_request(
worker        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
worker        |     raise exc
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
worker        |     stream = self._connect(request)
worker        |              ^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
worker        |     stream = self._network_backend.connect_tcp(**kwargs)
worker        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
worker        |     with map_exceptions(exc_map):
worker        |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
worker        |     self.gen.throw(typ, value, traceback)
worker        |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
worker        |     raise to_exc(exc) from exc
worker        | httpcore.ConnectError: [Errno -2] Name or service not known
worker        | 
worker        | The above exception was the direct cause of the following exception:
worker        | 
worker        | Traceback (most recent call last):
worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
worker        |     R = retval = fun(*args, **kwargs)
worker        |                  ^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
worker        |     return self.run(*args, **kwargs)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/code/celery_worker.py", line 187, in process_integration_brain_sync
worker        |     integrations = integration.get_integration_brain_by_type_integration("notion")
worker        |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/code/modules/brain/repository/integration_brains.py", line 110, in get_integration_brain_by_type_integration
worker        |     .execute()
worker        |      ^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 58, in execute
worker        |     r = self.session.request(
worker        |         ^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
worker        |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
worker        |     response = self._send_handling_auth(
worker        |                ^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
worker        |     response = self._send_handling_redirects(
worker        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
worker        |     response = self._send_single_request(request)
worker        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
worker        |     response = transport.handle_request(request)
worker        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
worker        |     with map_httpcore_exceptions():
worker        |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
worker        |     self.gen.throw(typ, value, traceback)
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
worker        |     raise mapped_exc(message) from exc
worker        | httpx.ConnectError: [Errno -2] Name or service not known
