### ISSUE TITLE
How to change the access URL of the app from http://localhost:3000/login to http://local.example.com:3000/login.

### ISSUE THREAD

**Issue by wangshuai-wuhan** [QuivrHQ/quivr#2385]
### The Feature

How to change the access URL of the app from http://localhost:3000/login to http://local.example.com:3000/login.

### Motivation, pitch

http://local.example.com  Setting up a proxy is more convenient.

**Comment by StanGirard** [comment]
Hey my friend you could follow and adapt -> https://docs.quivr.app/deployment/digital_ocean
