### ISSUE TITLE
backend-core error in  "http://localhost:5050/user/identity"  [Bug]: 

### ISSUE THREAD

**Issue by Techno-Trek** [QuivrHQ/quivr#2454]
### What happened?

It was expected that the Quivr application would function correctly, but with the errors, it is not possible to create brains, for example.

### Relevant log output

```bash
Installation: Ubuntu 22
The installation guide from the Quivr GitHub page was followed.

The installation proceeds smoothly without errors, and the installation of supabse also presents no issues.

The error is verified when attempting to create a brain, and inspecting the page in Google Chrome, it's possible to see that the error occurs at "http://localhost:5050/brains/" with the message "Not authenticated".
```

**Comment by Braga-source** [comment]
@dosu-bot

"It was done the alterations that were suggested but the problem persists.
Configuration of the .env file:"

#### QUIVR Configuration
# This file is used to configure the Quivr stack. It is used by the `docker-compose.yml` file to configure the stack.

# OPENAI. Update this to use your API key. To skip OpenAI integration use a fake key, for example: tk-aabbccddAABBCCDDEeFfGgHhIiJKLmnopjklMNOPqQqQqQqQ
OPENAI_API_KEY=sk-voCNLgel8xcjYElMaU1qT3

# LOCAL
# OLLAMA_API_BASE_URL=http://host.docker.internal:11434 # Uncomment to activate ollama. This is the local url for the ollama api

########
# FRONTEND
########

NEXT_PUBLIC_ENV=local
NEXT_PUBLIC_BACKEND_URL=http://localhost:5050
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
NEXT_PUBLIC_CMS_URL=https://cms.quivr.app
NEXT_PUBLIC_FRONTEND_URL=http://localhost:*
NEXT_PUBLIC_AUTH_MODES=magic_link,google_sso,password



########
# BACKEND
########

SUPABASE_URL=http://host.docker.internal:54321
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
PG_DATABASE_URL=notimplementedyet
ANTHROPIC_API_KEY=null
JWT_SECRET_KEY=super-secret-jwt-token-with-at-least-32-characters-long
AUTHENTICATE=true
TELEMETRY_ENABLED=true
CELERY_BROKER_URL=redis://redis:6379/0
CELEBRY_BROKER_QUEUE_NAME=quivr-preview.fifo
QUIVR_DOMAIN=http://localhost:3000/

**Comment by StanGirard** [comment]
Hey my friend, can you try to git pull and rerun the `docker compose up` ?

Or else, follow this procedure if on your own vps: https://docs.quivr.app/deployment/digital_ocean
