### ISSUE TITLE
[Bug]: Knowledge articles are not being used

### ISSUE THREAD

**Issue by marcato15** [QuivrHQ/quivr#2486]
### What happened?

I finally setup Quivr using ollama/lama2, and added a bunch of pdf's about malaria. However, when I ask questions it seems to have no knowledge of the sources I added to the brain. When I ask questions about malaria it's answering using knowledge from what I presume is the base LLM but when I asked to show sources it just responds it has none. Is there a minimum number of documents to add? I wish it would only respond using the documents I give it. I don't want it responding using general knowledge.

### Relevant log output

```bash
worker        | [2024-04-24 14:43:30,527: INFO/ForkPoolWorker-1] HTTP Request: POST http://host.docker.internal:54321/rest/v1/vectors?columns=%22content%22%2C%22embedding%22%2C%22metadata%22%2C%22id%22 "HTTP/1.1 400 Bad Request"
worker        | [ERROR] packages.embeddings.vectors [vectors.py:23]: Error creating vector for document {'code': '22000', 'details': None, 'hint': None, 'message': 'expected 1536 dimensions, not 4096'}
worker        | [2024-04-24 14:43:30,533: WARNING/ForkPoolWorker-1] Error processing file: 'NoneType' object is not iterable
worker        | [2024-04-24 14:43:30,542: INFO/ForkPoolWorker-1] HTTP Request: PATCH http://host.docker.internal:54321/rest/v1/notifications?id=eq.40538142-6bb4-4a28-9f36-e5e84029b6c4 "HTTP/1.1 200 OK"
worker        | [2024-04-24 14:43:30,551: INFO/ForkPoolWorker-1] HTTP Request: PATCH http://host.docker.internal:54321/rest/v1/brains?brain_id=eq.678c3ece-377f-46b3-9c82-e2dd67715796 "HTTP/1.1 200 OK"
worker        | [2024-04-24 14:43:30,552: INFO/ForkPoolWorker-1] Task process_file_and_notify[96451d30-c937-40bc-8fbc-fd3636f9b6b4] succeeded in 58.662878985000134s: True
```

**Comment by StanGirard** [comment]
The issue is the document weren't correctly embedded because you used Ollama :/ 

Please delete all data in the tables and start again.

**Comment by JerryKwan** [comment]
It seems like the vector is not match, the schema defined is something like
-- Create vectors table
CREATE TABLE IF NOT EXISTS vectors (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    content TEXT,
    file_sha1 TEXT,
    metadata JSONB,
    embedding VECTOR(1536)
);

But the vector generated is 4096

**Comment by JerryKwan** [comment]
You can use the following statement to alter the table
alter table vectors alter column embedding type vector(4096);

**Comment by mkhludnev** [comment]
to adjust vector dimensions, rename https://github.com/QuivrHQ/quivr/blob/main/backend/supabase/migrations/local_20240107152745_ollama.sql before starting supabase or run migration after renaming
also see #2690
