### ISSUE TITLE
[Bug]: Api Not authenticated

### ISSUE THREAD

**Issue by philiprcleary** [QuivrHQ/quivr#2500]
### What happened?

I am trying to interact with quivr via the api endpoint but I can't find how to get the access token. Every request understandably returns "No authenticated". Also, the api documentation has been removed from the docs. Why?

**Comment by StanGirard** [comment]
Hey! 

You need to create an api key from the frontend in the user page :) 

The documentation is here: https://api.quivr.app/docs
