### ISSUE TITLE
[Bug]: Unable to Access Login Page and Enter Credentials

### ISSUE THREAD

**Issue by gorfist** [QuivrHQ/quivr#2546]
### What happened?

I am facing an issue with the login page when running the Quivr application locally using Docker Compose. Instead of seeing a functional login page where I can enter my username and password, I am being redirected to a page with the title "Talk to Quivr" and a message stating "Upload users have access to a free and limited demo of Quivr".
Here are the details of the problem:

![quivr](https://github.com/QuivrHQ/quivr/assets/73386125/2118ab94-eae8-42f9-ad5d-aa57566c7623)

I followed the install instructions exactly and when I access the application at http://localhost:3000, I expect to see a login page where I can enter my credentials.
However, I am automatically redirected to a page with the title "Talk to Quivr" and a message about limited demo access for upload users.
I am unable to find any input fields or buttons to enter my username and password on this page.
The console output shows some warnings and errors related to authentication, including 403 Forbidden errors for requests to endpoints like /user, /user/identity, and /user/credits.
There are also validation errors thrown by the UserIdentity model, indicating that the 'id' field is expected to be a valid UUID but is receiving None.

To reproduce this issue:

Clone the Quivr repository and navigate to the project directory.
Update the .env file with the necessary configuration values.
Run docker-compose up to start the application.
Access the application at http://localhost:3000.

I have already tried the following:

Verified that the frontend and backend containers are running without any startup errors.
Double-checked the .env file to ensure the required configuration values are set correctly, especially those related to authentication and Supabase.
Reviewed the console output for any relevant error messages or warnings.

I suspect that there might be an issue with the authentication flow or the routing logic in the frontend application. It seems that the application is not properly redirecting to the login page and is instead showing a different page altogether.
I would greatly appreciate any assistance in identifying the root cause of this issue and providing guidance on how to resolve it. I need to be able to access the login page and enter my credentials to proceed with using the Quivr application.
Please let me know if you require any additional information or if there are any specific files or code snippets that would be helpful for investigating this issue further.
Thank you for your support!

### Relevant log output

```bash
backend-core  | INFO:     127.0.0.1:46698 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:47924 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:39582 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:45868 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.18.0.1:45880 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.18.0.1:45880 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.18.0.1:45868 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.18.0.1:45882 - "GET /user/credits HTTP/1.1" 403 Forbidden
```

**Comment by powderblock** [comment]
Same here

**Comment by va9** [comment]
Have the same issue - seems to be related to the fact that the backend is not running.
1. http://localhost:5050/docs -- "localhost didn’t send any data. ERR_EMPTY_RESPONSE"
2. The login page calls http://localhost:5050/user and http://localhost:5050/user/identity -- and is getting empty responses. Is there a way to debug backend start?

**Comment by va9** [comment]
> Have the same issue - seems to be related to the fact that the backend is not running.
> 
> 1. http://localhost:5050/docs -- "localhost didn’t send any data. ERR_EMPTY_RESPONSE"
> 2. The login page calls http://localhost:5050/user and http://localhost:5050/user/identity -- and is getting empty responses. Is there a way to debug backend start?

Managed to get the backend up 
```
docker compose pull
docker compose up
```

but now these calls to  http://localhost:5050/user and http://localhost:5050/user/identity are returning 403  {"detail": "Not authenticated" } and yet seeing a blank login page.

Any pointers are appreciated.

**Comment by HenrikBaltazar** [comment]
same issue with Fedora 39 and docker 26.0.1.
installled exactly as README says, @StanGirard is it lacking something besides README?

**Comment by StanGirard** [comment]
Last commit fixed it :/

**Comment by wwjCMP** [comment]
> Last commit fixed it :/

Does the latest version solve this problem?

**Comment by masapasa** [comment]
I still have this problem. Any solution to this? @StanGirard

**Comment by thunguyen1012** [comment]
In my case, the database was not created yet.

Fixing steps:
1. Update quivr - follow https://docs.quivr.app/install#updating-quivr
2. Excuse \backend\supabase\seed.sql to create admin user
