### ISSUE TITLE
[Bug]: While creating a new brain in localhost instance of Quivr, I am getting error

### ISSUE THREAD

**Issue by GSrinivasKishanLal** [QuivrHQ/quivr#2547]
### What happened?

Error occurred while creating a brain

Getting response:
Internal Server Error

kindly suggest on any solution to resolve

### Relevant log output

```bash
500
Internal Server Error.

CORS missing allow origin.
```

**Comment by GSrinivasKishanLal** [comment]
Thank you for your kind reply, but the issue is still existing with CORS issue occurring for also:

http://localhost:5050/user

**Comment by GSrinivasKishanLal** [comment]
Any solution for this also is required, kindly suggest

**Comment by GSrinivasKishanLal** [comment]
@dosu
The CORS issue is fixed for almost all other endpoints with ports except for the one given below:


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5050/chat/b55ab619-9838-4d33-be80-1d80d7226f58/question/stream?brain_id=40ba47d7-51b2-4b2a-9247-89e29619efb0. (Reason: CORS request did not succeed). Status code: (null).


Where the HTTP method used is : POST and I am facing this issue in the application. 


Receive "Type Error: Network Error when attempting to fetch resource." in the web page and "NS_ERROR_NET_PARTIAL_TRANSFER"


Kindly request you to give a suggestion on how this issue could be fixed.

**Comment by gsrinivaskishan** [comment]
@dosu, issue is still existing after trying all above steps, kindly suggest a solution

**Comment by GSrinivasKishanLal** [comment]
@dosu and others, kindly suggest on a solution, this is the error I am getting before the "add_cors_middleware(app)" function is called in main.py file:

backend-core  |     raise errors_.ConfigError(f'unable to infer type for attribute "{self.name}"')
backend-core  | pydantic.v1.errors.ConfigError: unable to infer type for attribute "api_key"

**Comment by GSrinivasKishanLal** [comment]
Error I get when I try to change the language model in existing brain:

backend-core  | ValueError: Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f14651a3990>: Failed to establish a new connection: [Errno 111] Connection refused'))

backend-core  | INFO:     172.19.0.1:36272 - "GET /knowledge?brain_id=40ba47d7-51b2-4b2a-9247-89e29619efb0 HTTP/1.1" 200 OK

backend-core  | INFO:     127.0.0.1:36282 - "GET /healthz HTTP/1.1" 200 OK
----------------------------------------------------------------------------------------------------------------
And, how to skip open AI API Key and use local Ollama.

Kindly suggest

**Comment by GSrinivasKishanLal** [comment]
@dosu, kindly suggest on where I shall find this "get_embeddings" function?

**Comment by GSrinivasKishanLal** [comment]
@dosu, kindly request you to help me with the below issue, I am having this when changing model to existing brain.


{"message":"Network Error","name":"AxiosError","stack":"U@[http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:86672\n7908/tT.xhr</</c.onerror@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:101022\nEventHandlerNonNull*7908/tT.xhr</<@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:100999\n7908/tT.xhr<@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:99480\ntR@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:103493\npromise](http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:86672/n7908/tT.xhr%3C/%3C/c.onerror@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:101022/nEventHandlerNonNull*7908/tT.xhr%3C/%3C@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:100999/n7908/tT.xhr%3C@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:99480/ntR@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:103493/npromise) callback*_request@[http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:107164\nrequest@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:105865\n7908/</e/<@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:107825\n7908/a/<@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:81381\n_@http://localhost:3000/_next/static/chunks/4957-275cd92484b2807d.js:1:10686\nupdateBrain@http://localhost:3000/_next/static/chunks/4957-275cd92484b2807d.js:1:11275\nx@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:33926\nonChange@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:27566\nw@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:44837\nonClick@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:45712\naS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:71761\naN@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:71915\n38790/sw/<@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:138576\nsw@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:138675\nsS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139091\n38790/sN/<@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:145234\noK@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:92812\niL@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:122042\nsN@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:140399\nuE@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:129850\nuS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:129638\nEventListener.handleEvent*sP@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139888\nsE@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139287\n38790/sz/<@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139453\nsz@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139398\n38790/t.hydrateRoot@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:169528\n70945/C/<@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5292\n45060/t.startTransition@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:95613\nC@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5262\n35317/<@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5710\nr@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:1962\nr@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:2323\n35317@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5663\nl@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:151\nn@http://localhost:3000/_next/static/chunks/main-app-4d1564f0311960d9.js:1:395\n@http://localhost:3000/_next/static/chunks/main-app-4d1564f0311960d9.js:1:442\nl.O@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:551\nc@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:4290\n@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:64\n","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json](http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:107164/nrequest@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:105865/n7908/%3C/e/%3C@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:107825/n7908/a/%3C@http://localhost:3000/_next/static/chunks/511-fa8e22a6a59a624c.js:6:81381/n_@http://localhost:3000/_next/static/chunks/4957-275cd92484b2807d.js:1:10686/nupdateBrain@http://localhost:3000/_next/static/chunks/4957-275cd92484b2807d.js:1:11275/nx@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:33926/nonChange@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:27566/nw@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:44837/nonClick@http://localhost:3000/_next/static/chunks/app/studio/%5BbrainId%5D/page-713d49bd3beb26d9.js:1:45712/naS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:71761/naN@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:71915/n38790/sw/%3C@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:138576/nsw@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:138675/nsS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139091/n38790/sN/%3C@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:145234/noK@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:92812/niL@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:122042/nsN@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:140399/nuE@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:129850/nuS@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:129638/nEventListener.handleEvent*sP@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139888/nsE@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139287/n38790/sz/%3C@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139453/nsz@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:139398/n38790/t.hydrateRoot@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:169528/n70945/C/%3C@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5292/n45060/t.startTransition@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:95613/nC@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5262/n35317/%3C@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5710/nr@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:1962/nr@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:2323/n35317@http://localhost:3000/_next/static/chunks/8069-cb25729d0aba5a55.js:1:5663/nl@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:151/nn@http://localhost:3000/_next/static/chunks/main-app-4d1564f0311960d9.js:1:395/n@http://localhost:3000/_next/static/chunks/main-app-4d1564f0311960d9.js:1:442/nl.O@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:551/nc@http://localhost:3000/_next/static/chunks/webpack-ce3f0d52084a8e75.js:1:4290/n@http://localhost:3000/_next/static/chunks/fd9d1056-0033f815a828ffe8.js:1:64/n%22,%22config%22:%7B%22transitional%22:%7B%22silentJSONParsing%22:true,%22forcedJSONParsing%22:true,%22clarifyTimeoutError%22:false%7D,%22adapter%22:[%22xhr%22,%22http%22],%22transformRequest%22:[null],%22transformResponse%22:[null],%22timeout%22:0,%22xsrfCookieName%22:%22XSRF-TOKEN%22,%22xsrfHeaderName%22:%22X-XSRF-TOKEN%22,%22maxContentLength%22:-1,%22maxBodyLength%22:-1,%22env%22:%7B%7D,%22headers%22:%7B%22Accept%22:%22application/json), text/plain, */*","Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE1NjkyMTYyLCJpYXQiOjE3MTU2ODg1NjIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMjEvYXV0aC92MSIsInN1YiI6IjM5NDE4ZTNiLTAyNTgtNDQ1Mi1hZjYwLTdhY2ZjYzEyNjNmZiIsImVtYWlsIjoiYWRtaW5AcXVpdnIuYXBwIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTU2ODg1NjJ9XSwic2Vzc2lvbl9pZCI6ImJhMTVkYWQ3LTY5ZGMtNGU4Yy1hYWUzLTk3MDM4NzdmMjFmMCIsImlzX2Fub255bW91cyI6ZmFsc2V9.5x8LtEnOXG-O9s3t-G-YqIVIiQccotuf0UbPJ9s0ses"},"baseURL":"http://localhost:5050","method":"put","url":"/brains/40ba47d7-51b2-4b2a-9247-89e29619efb0/","data":"{\"name\":\"Default brain\",\"description\":\"This is a description\",\"model\":\"ollama-phi3:latest\",\"prompt\":{\"title\":\"\",\"content\":\"\"},\"brain_id\":\"40ba47d7-51b2-4b2a-9247-89e29619efb0\",\"status\":\"private\",\"last_update\":\"2024-04-01T18:03:45.348384\",\"brain_type\":\"doc\",\"isApiDefinitionReadOnly\":false,\"isUpdatingApiDefinition\":true,\"max_tokens\":1000}"},"code":"ERR_NETWORK","status":null}

**Comment by gsrinivaskishan** [comment]
Error Message:
1) "Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n

2) CSP issue when using 127.0.0.1:3000 to login in frontend

@dosu Kindly suggest solutions

**Comment by Amirjab21** [comment]
I'm getting this too - seems like maybe the CORS policy doesn't work with Docker?

**Comment by saitho** [comment]
Same issue here :( Both in Chrome and Firefox

**Comment by saitho** [comment]
I feel this is an issue that needs to be worked on, otherwise the software is unusable going by the installation instructions.
