### ISSUE TITLE
LocalAI support

### ISSUE THREAD

**Issue by netandreus** [QuivrHQ/quivr#2565]
### The Feature

Can you please add settings for OpenAI server (url).

### Motivation, pitch

With this we can point Quivr to LocalAI server.

**Comment by bioshazard** [comment]
Was just lookin for this support. Will add it myself if someone doesn't beat me to it.

**Comment by wwjCMP** [comment]
Yes, it is very necessary.

**Comment by bioshazard** [comment]
I have had a ton of trouble getting Quivr up in the first place. It will be simple to add once I get a working environment. 

Directly in code, you should just need `base_url=http://localhost:8080/v1` (or wherever LocalAI is hosted) added as an option in the ChatOpenAI line here:

https://github.com/QuivrHQ/quivr/blob/main/backend/modules/brain/integrations/GPT4/Brain.py#L170

**Comment by bioshazard** [comment]
FYI: They have support for overriding the base url in the models table, so LocalAI is supported.
