### ISSUE TITLE
[Epic]: Where does the user change the language?

### ISSUE THREAD

**Issue by rotterdamdaddy** [QuivrHQ/quivr#2597]
### Why do we need this functionality?

Hello, I am not able to change the language from English to another language. I need help.

### What are we developing?

#

### What are the validation criteria to validate this feature?

#

### What's out of scope for this feature?

#

### Should this feature be feature flagged?

- [ ] Feature Flagged

### How are we going to code this feature?

#

### Are there any technical decisions made that should be shared?

#

### What is preventing us from delivering this feature?

#

### What can the feature potentially break?

#

**Comment by rotterdamdaddy** [comment]
@dosu no I mean when im on the website, the website is already running. but how do I change the language from English to Spanish?

**Comment by MakeTooRRSS** [comment]
Hello could you finally put the language selector? I have the same problem, there are different languages but you can not put another language on the site. Can someone help me? Thanks
