### ISSUE TITLE
[Bug]: it's still using OpenAI after set Ollama in .env file

### ISSUE THREAD

**Issue by esponiyo** [QuivrHQ/quivr#2599]
### What happened?

Modifying .env file to use Ollama:
1.- Using a fake key to skip OpenAI integration 
2.- OLLAMA_API_BASE_URL=http://host.docker.internal:11434
3.- Compose again with rebuild

Checks:
1.- Ollama server running and checked with line command
2.- Quivr: Embeddings for uploaded docs are done with Ollama
3.- Quivr: Chat is still trying with OpenAI, of course with error in frontend because of fake api
4.- Error log (attached) shows what is obvious

### Relevant log output

```bash
backend-core  |     | litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: tk-aabbc***************************************qQqQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}} 
backend-core  |     | Model: gpt-3.5-turbo-0125
backend-core  |     | API Base: https://api.openai.com
```

### NOTE:
This seems to be a bug and what is worse, a security fault, because chunks of private documents could be uploaded to OpenAI, if api was correct, as part of the behavior of a RAG flow.

**Comment by esponiyo** [comment]
### Please consider this issue as a possible security fault.

### A serious one: 
User testing with private documents could expose private chunks of those documents to OpenAI, thinking that all data is still on-premise.

**Comment by mkhludnev** [comment]
my understanding that you need configure model https://docs.quivr.app/configuring/new-model and the model name should be prepended with `ollama/` prefix. In this case LiteLLM turns to ollama URL.
