### ISSUE TITLE
[Feature]: email RAG

### ISSUE THREAD

**Issue by mikestaub** [QuivrHQ/quivr#2632]
### The Feature

I would like to connect my brain to an IMAP server to ask it questions about all the emails.

### Motivation, pitch

This is an obviously useful feature. See this tool for inspiration: https://github.com/riensen/Auto-GPT-Email-Plugin

### Twitter / LinkedIn details

@mikestaub

**Comment by StanGirard** [comment]
Coming soon my friend :)

**Comment by mikestaub** [comment]
Can you reopen this? This is the most important feature for me.
