### ISSUE TITLE
[Bug]: failed to fetch;failed to connect 54323,but 5050 report status ok

### ISSUE THREAD

**Issue by HarrietW221b** [QuivrHQ/quivr#2639]
### What happened?

A bug happened!
http://localhost:3000/login,After I entered my account and password,web report "failed to fetch". And I checked the [5050](http://localhost:5050/), it said"{"status":"OK"}".but i failed to connect the http://localhost:54323/,it said "Unable to access this website. Localhost refused our connection request."
![image](https://github.com/QuivrHQ/quivr/assets/171697801/315074b3-e3f0-427b-81f5-d654b0d1def4)

### Relevant log output

```bash
worker        |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
worker        |     raise mapped_exc(message) from exc
worker        | httpx.ConnectError: [Errno 111] Connection refused
backend-core  | INFO:     172.26.0.1:45280 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45282 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45282 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45280 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45280 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45282 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45282 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     172.26.0.1:45280 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     127.0.0.1:57488 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:41430 - "GET /healthz HTTP/1.1" 200 OK
```

**Comment by HarrietW221b** [comment]
@dosu.How to make sure that my frontend is correctly configured to use the backend URL? and how to do this"Based on the provided useFetch hook, make sure that the NEXT_PUBLIC_BACKEND_URL environment variable is set correctly and that the authorization headers are being included in your fetch requests"?can you be more explicit and like step by step?

**Comment by StanGirard** [comment]
Make sure supabase is started with `supabase start` by run it in the `backend` folder

**Comment by zulfaiflakhul** [comment]
@StanGirard 

How i can add authentication in supabase dashboard?
