### ISSUE TITLE
How do I run the Ollama [Bug]: 

### ISSUE THREAD

**Issue by FaizanMunsaf** [QuivrHQ/quivr#2777]
### What happened?

I am trying to run Ollama there's no specific command I found that run Ollama private model.
There's any further guidance available with current repo?

### Relevant log output

```bash
Just looking forward to Ollama show into my bot, I will generate my answer using Ollama llama3-8b model!
```

**Comment by roaidev** [comment]
real problem is getting it to work with llama3. how do we do that?

**Comment by tomgeorgekap** [comment]
how to run with llama3

**Comment by c4801725870** [comment]
If you look at the "brains" table there is a "model" column and they don't give you a way to change the model initially - the code will default to gpt-3.5-turbo-0125 if this value is NULL. so put "ollama/llama2" in the row for your brain under the model column. unfortunately i get a new error, openai.NotFoundError: 404 page not found... it looks like it is still trying to use openAI for some reason. 

`backend-core  | [INFO] quivr_api.modules.chat.controller.chat.utils [utils.py:79]: Model to use: name='ollama/llama2' price=1 max_input=10000 max_output=1000
backend-core  | [INFO] quivr_api.modules.user.service.user_usage [user_usage.py:80]: Request count is 0, creating new record
backend-core  | [INFO] quivr_api.packages.utils.telemetry [telemetry.py:35]: Domain: localhost
backend-core  | INFO:     172.18.0.1:47844 - "POST /chat/a1fd29ce-4ada-4908-b95e-c6b63044fa30/question/stream?brain_id=b9a2ffb0-3c8f-486c-bcaa-e15958807732 HTTP/1.1" 200 OK
backend-core  | [INFO] quivr_api.modules.rag_service.rag_service [rag_service.py:233]: Creating question for chat a1fd29ce-4ada-4908-b95e-c6b63044fa30 with brain b9a2ffb0-3c8f-486c-bcaa-e15958807732 
backend-core  | INFO:     172.18.0.1:47828 - "GET /chat HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:47858 - "OPTIONS /chat/a1fd29ce-4ada-4908-b95e-c6b63044fa30/history HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:47828 - "GET /onboarding HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:47816 - "GET /user HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:47848 - "GET /user/identity HTTP/1.1" 200 OK
backend-core  | INFO:     172.18.0.1:47864 - "GET /chat/a1fd29ce-4ada-4908-b95e-c6b63044fa30/history HTTP/1.1" 200 OK
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 265, in __call__
backend-core  |     await wrap(partial(self.listen_for_disconnect, receive))
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
backend-core  |     await func()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
backend-core  |     message = await receive()
backend-core  |               ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
backend-core  |     await self.message_event.wait()
backend-core  |   File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
backend-core  |     await fut
backend-core  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 788793476810
backend-core  | 
backend-core  | During handling of the above exception, another exception occurred:
backend-core  | 
backend-core  |   + Exception Group Traceback (most recent call last):
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
backend-core  |   |     result = await app(  # type: ignore[func-returns-value]
backend-core  |   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
backend-core  |   |     return await self.app(scope, receive, send)
backend-core  |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend-core  |   |     await super().__call__(scope, receive, send)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
backend-core  |   |     await self.middleware_stack(scope, receive, send)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend-core  |   |     raise exc
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend-core  |   |     await self.app(scope, receive, _send)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
backend-core  |   |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
backend-core  |   |     await self.app(scope, receive, send)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
backend-core  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |   |     raise exc
backend-core  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |   |     awai`

**Comment by c4801725870** [comment]
I got further along, the 404 error is from quivr_api/modules/rag_service/rag_service.py, change line 92 and add + "/v1" to ollama_url in the llm_base_url assignment.

                llm_base_url=ollama_url + "/v1",

now I get a different error, it just says the model is not found


 | openai.NotFoundError: Error code: 404 - {'error': {'message': 'model "ollama/llama2" not found, try pulling it first', 'type': 'api_error', 'param': None, 'code': None}}

so the API working, we just sent it a bad model. it probably expects "llama2"

so change line 91 

                model="llama2",

hardcode it, who cares for now.

thus, now, is working. 

it is complete

![image](https://github.com/user-attachments/assets/344560a2-a079-44c6-8867-73ed52fc3314)

**Comment by c4801725870** [comment]
> real problem is getting it to work with llama3. how do we do that?

as long as the API works the same you literally just type in llama3 wherever you put llama2 before.

**Comment by PFLigthart** [comment]
@c4801725870 I have tried and still cannot seem to get it to work. Here is my complete process I just followed:

- Already have ollama installed and have llama3.1 locally which works and is running in a terminal

- Download docker desktop (I got 4.32.0)
- git clone https://github.com/quivrhq/quivr.git && cd quivr
- cp .env.example .env
- vim .env
- Comment OPENAI_API_KEY, uncomment Ollama
- vim docker-compose.yml
- Change line 53 from backend-base:latest -->stangirard/quivr-backend-prebuilt:latest
- cd backend && supabase start
- cd ../
- docker compose pull
- docker compose up
- Go to localhost:3000
- Sign in with admin@quivr.app -> password: admin
- Create username and fill in the details on the Welcome to quivr popup
- Go to localhost:54323
- Update user_settings table models column to read ["gpt-3.5-turbo-0125", "gpt-4-0125-preview", "ollama/llama3.1"]
- Go to quivr/api/quivr_api/modules/rag_service/rag_service.py, change line 92 and add + "/v1" to ollama_url in the llm_base_url assignment. (as indicated above)
- Also change line 91 to read model="llama3.1"
- Create a new brain using the auto-popup after the first sign-in
- Brain seems to be created correctly with a green popup confirmation (did change the brain to use ollama/llama3.1 from drop down)
- Data upload also seems to work correctly with a green popup
- Asking a question results in a Red popup "TypeError: network error"
- Start of terminal error:
backend-core  | [INFO] quivr_api.modules.chat.controller.chat_routes [chat_routes.py:212]: Creating question for chat 9c1eb*******814b with brain 926c******6a70 of type <class 'uuid.UUID'>
backend-core  | [INFO] quivr_api.modules.chat.controller.chat.utils [utils.py:79]: Model to use: name='gpt-3.5-turbo-0125' price=1 max_input=4000 max_output=1000
backend-core  | [INFO] quivr_api.modules.user.service.user_usage [user_usage.py:97]: User admin@quivr.app request count updated to 5

Seems to still want to use gpt-3.5. Any help is appreciated.
Cheers,

**Comment by c4801725870** [comment]
> @c4801725870 I have tried and still cannot seem to get it to work. Here is my complete process I just followed:
> 
> * Already have ollama installed and have llama3.1 locally which works and is running in a terminal
> * Download docker desktop (I got 4.32.0)
> * git clone https://github.com/quivrhq/quivr.git && cd quivr
> * cp .env.example .env
> * vim .env
> * Comment OPENAI_API_KEY, uncomment Ollama
> * vim docker-compose.yml
> * Change line 53 from backend-base:latest -->stangirard/quivr-backend-prebuilt:latest
> * cd backend && supabase start
> * cd ../
> * docker compose pull
> * docker compose up
> * Go to localhost:3000
> * Sign in with [admin@quivr.app](mailto:admin@quivr.app) -> password: admin
> * Create username and fill in the details on the Welcome to quivr popup
> * Go to localhost:54323
> * Update user_settings table models column to read ["gpt-3.5-turbo-0125", "gpt-4-0125-preview", "ollama/llama3.1"]
> * Go to quivr/api/quivr_api/modules/rag_service/rag_service.py, change line 92 and add + "/v1" to ollama_url in the llm_base_url assignment. (as indicated above)
> * Also change line 91 to read model="llama3.1"
> * Create a new brain using the auto-popup after the first sign-in
> * Brain seems to be created correctly with a green popup confirmation (did change the brain to use ollama/llama3.1 from drop down)
> * Data upload also seems to work correctly with a green popup
> * Asking a question results in a Red popup "TypeError: network error"
> * Start of terminal error:
>   backend-core  | [INFO] quivr_api.modules.chat.controller.chat_routes [chat_routes.py:212]: Creating question for chat 9c1eb***814b with brain 926c**6a70 of type <class 'uuid.UUID'>
>   backend-core  | [INFO] quivr_api.modules.chat.controller.chat.utils [utils.py:79]: Model to use: name='gpt-3.5-turbo-0125' price=1 max_input=4000 max_output=1000
>   backend-core  | [INFO] quivr_api.modules.user.service.user_usage [user_usage.py:97]: User [admin@quivr.app](mailto:admin@quivr.app) request count updated to 5
> 
> Seems to still want to use gpt-3.5. Any help is appreciated. Cheers,

my user_settings only includes ollama

![image](https://github.com/user-attachments/assets/59b1572f-d0ab-483d-9d37-9bb222373fb4)

also, in quivr_api/modules/chat/controller/chat/utils.py change line 45

`
    default_model = "ollama/llama2"
`
or whatever you want. 

as you can see they hardcoded it to the gpt-3.5 and there is no consideration for other models.

**Comment by c4801725870** [comment]
@PFLigthart i took another look to see if i can make it so i can switch models. Unfortunately we run into the issue that the "default model" referenced in quivr_api/modules/chat/controller/chat/utils.py is called upon brain creation, because the row in the Brains table defaults "model" to NULL. Also I thought it would be worth mentioning, you need to add the model to the models table, just adding a row for the new model.

I proved this by changing the code to use "brain_model" rather than "default_model". 
I created a new brain, but it submitted the data to the wrong model(it used the default model)

`# If brain.model is None, set it to the default_model
    if brain_model is None:
        brain_model = default_model
        
    model_to_use = LLMModel(  # TODO Implement default models in database
        name=brain_model, price=1, max_input=4000, max_output=1000
    )

    logger.debug("Brain model: %s", brain_model)


    is_brain_model_available = any(
        brain_model == model_dict.get("name") for model_dict in models_settings
    )

    is_user_allowed_model = brain_model in user_settings.get(
        "models", [brain_model]
    )  # Checks if the model is available in the list of models

    logger.debug(f"Brain model: {brain_model}")
    logger.debug(f"User models: {user_settings.get('models', [])}")
    logger.debug(f"Model available: {is_brain_model_available}")
    logger.debug(f"User allowed model: {is_user_allowed_model}")

    if is_brain_model_available and is_user_allowed_model:
        # Use the model from the brain
        model_to_use.name = brain_model
        for model_dict in models_settings:
            if model_dict.get("name") == model_to_use.name:
                model_to_use.price = model_dict.get("price")
                model_to_use.max_input = model_dict.get("max_input")
                model_to_use.max_output = model_dict.get("max_output")
                break

    logger.info(f"Model to use: {model_to_use}")

    return model_to_use`

for the quivr_api/modules/rag_service/rag_service.py change line 91 to 
`
                model=self.model_to_use.name.split('/')[1],
`
this last part will eliminate having to modify this code in the future. Now you just need to edit the default model when creating a new brain. 

The bad news I have so far is the new code seems really bad at tokenizing the data input when the brain is created. This project needs a lot of work.

**Comment by PFLigthart** [comment]
@c4801725870 this worked. Thank you so much. I was also able to get it to work with llama3 and llama3.1 by hardcoding the relevant entries. Appreciate it.
Cheers.

**Comment by caishanli** [comment]
> > @c4801725870 I have tried and still cannot seem to get it to work. Here is my complete process I just followed:
> > 
> > * Already have ollama installed and have llama3.1 locally which works and is running in a terminal
> > * Download docker desktop (I got 4.32.0)
> > * git clone https://github.com/quivrhq/quivr.git && cd quivr
> > * cp .env.example .env
> > * vim .env
> > * Comment OPENAI_API_KEY, uncomment Ollama
> > * vim docker-compose.yml
> > * Change line 53 from backend-base:latest -->stangirard/quivr-backend-prebuilt:latest
> > * cd backend && supabase start
> > * cd ../
> > * docker compose pull
> > * docker compose up
> > * Go to localhost:3000
> > * Sign in with [admin@quivr.app](mailto:admin@quivr.app) -> password: admin
> > * Create username and fill in the details on the Welcome to quivr popup
> > * Go to localhost:54323
> > * Update user_settings table models column to read ["gpt-3.5-turbo-0125", "gpt-4-0125-preview", "ollama/llama3.1"]
> > * Go to quivr/api/quivr_api/modules/rag_service/rag_service.py, change line 92 and add + "/v1" to ollama_url in the llm_base_url assignment. (as indicated above)
> > * Also change line 91 to read model="llama3.1"
> > * Create a new brain using the auto-popup after the first sign-in
> > * Brain seems to be created correctly with a green popup confirmation (did change the brain to use ollama/llama3.1 from drop down)
> > * Data upload also seems to work correctly with a green popup
> > * Asking a question results in a Red popup "TypeError: network error"
> > * Start of terminal error:
> >   backend-core  | [INFO] quivr_api.modules.chat.controller.chat_routes [chat_routes.py:212]: Creating question for chat 9c1eb***814b with brain 926c**6a70 of type <class 'uuid.UUID'>
> >   backend-core  | [INFO] quivr_api.modules.chat.controller.chat.utils [utils.py:79]: Model to use: name='gpt-3.5-turbo-0125' price=1 max_input=4000 max_output=1000
> >   backend-core  | [INFO] quivr_api.modules.user.service.user_usage [user_usage.py:97]: User [admin@quivr.app](mailto:admin@quivr.app) request count updated to 5
> > 
> > Seems to still want to use gpt-3.5. Any help is appreciated. Cheers,
> 
> my user_settings only includes ollama
> 
> ![image](https://private-user-images.githubusercontent.com/129828180/353254807-59b1572f-d0ab-483d-9d37-9bb222373fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzI1MDEsIm5iZiI6MTcyNDE3MjIwMSwicGF0aCI6Ii8xMjk4MjgxODAvMzUzMjU0ODA3LTU5YjE1NzJmLWQwYWItNDgzZC05ZDM3LTliYjIyMjM3M2ZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNjQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTFlMDdlYzAxYjYyNzM5ZDI3NDIwOTQ2NmQyNWYzNDgwZjNhMDQzNzVjMDdjNmMwNDE5MzI5MmVlZmEzNmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wL3oaBs8aK_pR0b9rnjCjQTFL9-GFgSJAIt-Urc9cjg)
> 
> also, in quivr_api/modules/chat/controller/chat/utils.py change line 45
> 
> `default_model = "ollama/llama2"` or whatever you want.
> 
> as you can see they hardcoded it to the gpt-3.5 and there is no consideration for other models.

the lastest version has no models column in user_settings table, but has a new table named models. So I add ollama mistral model to this table, but when I send ask a question in quivr, the error is "TypeError : network error", and in ollama log, it received a post request with uri of "/chat/completions", post data is ok with model name "mistra", but as [https://github.com/ollama/ollama?tab=readme-ov-file#chat-with-a-model](ollama chat-with-a-model) says, quivr should post to uri of "/api/chat". So is the uri "/chat/completions" correct?

**Comment by c4801725870** [comment]
@caishanli need to make sure the model in models table has ollama/ as part of the string, literally ollama/mistral for example. While reading the code i notice it only detects ollama if it actually finds ollama as part of the model string. Simply putting mistral for model will detect as GPT and probably use wrong API which you experienced. This is why line 91 need to use string.split method to extract model type. If I just changed to llama3 instead of ollama/llama3 it would not hit that branch of code... Again this project needs a lot of work and you need to carefully examine the code to get it functioning. It is not in the author's interest to produce a repo that allows full offline functionality out of the box for free.

**Comment by caishanli** [comment]
> @caishanli need to make sure the model in models table has ollama/ as part of the string, literally ollama/mistral for example. While reading the code i notice it only detects ollama if it actually finds ollama as part of the model string. Simply putting mistral for model will detect as GPT and probably use wrong API which you experienced. This is why line 91 need to use string.split method to extract model type. If I just changed to llama3 instead of ollama/llama3 it would not hit that branch of code... Again this project needs a lot of work and you need to carefully examine the code to get it functioning. It is not in the author's interest to produce a repo that allows full offline functionality out of the box for free.

Thank you for your reply! I tested ollama/mistral, the result is the same. The main problem is that quivr send wrong post data to ollama, shortly quivr use the wrong ollama rest api, so ollama can't reply correctly. 
And code is not same as the , so how did the pull requester test this code?

**Comment by yukha-dw** [comment]
> edit: the reason was the API base url is different for actually chatting with the bot. look at my post below for the solution. i don't know if this was a coincidence because ollama2 API is now compatible with openai format. And at first glance it looks like the code is still hardcoded to use ChatOpenAI, see backend/core/quivr_core/llm/llm_endpoint.py
_llm = ChatOpenAI( model=config.model, api_key=SecretStr(config.llm_api_key) if config.llm_api_key else None, base_url=config.llm_base_url, )

mine does not working so I have to import `ChatOllama from langchain_community.chat_models` then replace `_llm = ChatOpenAI(model=config.model` with `_llm = ChatOllama(model="llama2"`. I haven't tested RAG functionality, it could be broken too

**Comment by aishock** [comment]
The Supabase has completely new interface now and I failed to configure llamma3.1 using the new Supabase. The column of "models" are removed from user settings and I have to add in Ollama from "models" table, but I can't manage to get it to work. Does anyone succeed to do that using the new Supabase?

**Comment by yukha-dw** [comment]
@aishock I believe I'm using same version as you. I also update the model on "models" table instead. But some of the codes need to be changed because they are hardcoded to OpenAI.
