### ISSUE TITLE
[Bug]: Error response from daemon: No such image: backend-base:latest

### ISSUE THREAD

**Issue by Techno-Trek** [QuivrHQ/quivr#2885]
### What happened?

After the last update I can no longer start building the quivr docker images.
The error is presented when executing the "docker compose up" command

System: Ubuntu Server 24.04 LTS

### Relevant log output

```bash
=> [frontend runner 7/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./                                              0.5s
 => [frontend runner 8/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static                                      0.0s
 => [frontend] exporting to image                                                                                                         0.3s
 => => exporting layers                                                                                                                   0.3s
 => => writing image sha256:fb07fbe90db961d2f09f593f666debf18b5eb03e7793b0728a2c6d5e1271d7bc                                              0.0s
 => => naming to docker.io/library/quivr-frontend-prebuilt                                                                                0.0s
[+] Running 6/3
 ✔ Network quivr_default   Created                                                                                                        0.1s
 ✔ Container redis         Created                                                                                                        0.0s
 ✔ Container backend-core  Created                                                                                                        0.0s
 ✔ Container web           Created                                                                                                        0.0s
 ✔ Container worker        Created                                                                                                        0.0s
 ✔ Container beat          Created                                                                                                        0.0s
 ⠋ Container notifier      Creating                                                                                                       0.0s
 ⠋ Container flower        Creating                                                                                                       0.0s
Error response from daemon: No such image: backend-base:latest
```

**Comment by Braga-source** [comment]
@dosu

running the command "docker compose up --build"
another error occurs:

=> CACHED [worker 12/13] COPY supabase /code/supabase/                                                                                   0.0s
 => ERROR [worker 13/13] RUN poetry install --no-root --with dev,test &&     playwright install --with-deps &&     rm -rf /tmp/poetry_ca  1.1s
------
 > [worker 13/13] RUN poetry install --no-root --with dev,test &&     playwright install --with-deps &&     rm -rf /tmp/poetry_cache:
0.555 Skipping virtualenv creation, as specified in config file.
0.655 Installing dependencies from lock file
1.019
1.019 pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
------
failed to solve: process "/bin/sh -c poetry install --no-root --with dev,test &&     playwright install --with-deps &&     rm -rf $POETRY_CACHE_DIR" did not complete successfully: exit code: 1

**Comment by Techno-Trek** [comment]
@dosu It didn't work, the error persists.


 => => exporting layers                                                                                                     0.0s
 => => writing image sha256:adc6af4a6bf70f6b39509eee94856ad2b84bc9fd96eaec8f98d2e8df4a52d2d6                                0.0s
 => => naming to docker.io/library/quivr-frontend-prebuilt                                                                  0.0s
[+] Running 5/6
 ✔ Network quivr_default   Created                                                                                          0.3s
 ✔ Container redis         Created                                                                                         10.3s
 ✔ Container backend-core  Created                                                                                         10.3s
 ⠋ Container web           Creating                                                                                         0.1s
 ✔ Container beat          Created                                                                                          0.1s
 ✔ Container worker        Created                                                                                          0.1s
 ⠋ Container flower        Creating                                                                                         0.0s
 ⠋ Container notifier      Creating                                                                                         0.0s
Error response from daemon: No such image: backend-base:latest

**Comment by lanyur** [comment]
So can the author be more rigorous? According to the README, it's impossible to achieve successful build.

**Comment by zdkderpphb** [comment]
@lanyur I also ran in this problem. After Codecheck i changed the Line with the image. Maybe a quick fix for you.

backend-base:latest to stangirard/quivr-backend-prebuilt:latest

**Comment by Techno-Trek** [comment]
@zdkderpphb Thank you very much. It apparently worked, I'm going to redo everything from the beginning to see if it will work correctly.

**Comment by lanyur** [comment]
> @lanyur I also ran in this problem. After Codecheck i changed the Line with the image. Maybe a quick fix for you.
> 
> backend-base:latest to stangirard/quivr-backend-prebuilt:latest

thank you,it's worked

**Comment by PFLigthart** [comment]
I also have this error.

**Comment by PFLigthart** [comment]
I also have the same error which is partially resolved by following @zdkderpphb recommendation. However, I am unable to get llama3 or 2 to work with ollama. I followed the instructions on the README exactly. I also checked issue #2777 but this does not solve my problems. Tried to get it working today and yesterday.

**Comment by c4801725870** [comment]
> I also have the same error which is partially resolved by following @zdkderpphb recommendation. However, I am unable to get llama3 or 2 to work with ollama. I followed the instructions on the README exactly. I also checked issue #2777 but this does not solve my problems. Tried to get it working today and yesterday.

hi, sorry about your troubles. see https://github.com/QuivrHQ/quivr/issues/2777 once again, i got it working

**Comment by atulgrover** [comment]
the docker-compose.yaml file should be updated with all "images:" directed to "stangirard/quivr-backend-prebuilt:latest"

**image: stangirard/quivr-backend-prebuilt:latest**
