### ISSUE TITLE
[Bug]: update error

### ISSUE THREAD

**Issue by johnfelipe** [QuivrHQ/quivr#2941]
### What happened?

A bug happened!

    git pull

Step 2: Update the migration

    supabase migration up

and something happen

    cannot read config in /home/felipe/Quivr: open supabase/config.toml: no such file or directory
    Have you set up the project with supabase init?

how can solve this?

**Comment by johnfelipe** [comment]
file is exactly same, pls give me more option for solve this issue:

    felipe@template:~$ cd Quivr/
    felipe@template:~/Quivr$ supabase migration up
    cannot read config in /home/felipe/Quivr: open supabase/config.toml: no such file or directory
    Have you set up the project with supabase init?

**Comment by StanGirard** [comment]
Hey my friend, please make sure you are in the `backend` folder when doing so 🙂
