### ISSUE TITLE
[Bug]: check_if_is_premium_user error

### ISSUE THREAD

**Issue by luqijun** [QuivrHQ/quivr#2976]
### What happened?

I got a error when execute celery task  `check_if_is_premium_user` in _celery_worker.py_.
when i open supabase table editor from [http://localhost:54323/project/default/editor,](http://localhost:54323/project/default/editor) I couldn't open the table _subscriptions_, and i got the error "Application error: a client-side exception has occurred (see the browser console for more information)."

![image](https://github.com/user-attachments/assets/21d11e0e-4b97-4819-bb2b-3425fbd59bf3)

### Relevant log output

```bash
Exception has occurred: APIError
{'code': 'XX000', 'details': None, 'hint': None, 'message': 'called `Result::unwrap()` on an `Err` value: InvalidPosition'}
  File "/home/Jun/Projects/Python/NLP/quivr/backend/api/quivr_api/celery_worker.py", line 165, in check_if_is_premium_user
    .execute()
     ^^^^^^^^^
postgrest.exceptions.APIError: {'code': 'XX000', 'details': None, 'hint': None, 'message': 'called `Result::unwrap()` on an `Err` value: InvalidPosition'}
```

**Comment by StanGirard** [comment]
Hi my friend, this is normal as we are also using this code for quivr.com. <br><br>In order to remove stripe and not have the errors please add `DEACTIVATE_STRIPE=true` to your `.env` file
