### ISSUE TITLE
[Feature]: JSON Document loader

### ISSUE THREAD

**Issue by atulgrover** [QuivrHQ/quivr#3010]
### The Feature

Please add JSON document parsing and uploading into SUPABASE feature... JSON enables metadata to be attached to each chunk of text (as compared to each document). 

https://python.langchain.com/v0.1/docs/modules/data_connection/document_loaders/json/

### Motivation, pitch

Adding JSON document support to QUIVR could be a game-changer and enable

1. **Versatile Data Integration:** JSON is increasingly becoming the preferred format for data interchange across various platforms and APIs. By adding JSON support, your RAG application can seamlessly integrate with a broader range of data sources, from web APIs to internal data pipelines, enabling richer, more diverse information retrieval.

2. **Granular Metadata Control:** JSON's hierarchical structure allows for attaching metadata not just to entire documents but to individual data chunks. This granular control enables more precise indexing and retrieval, enhancing the relevance and accuracy of the generated content.

3. **Enhanced Search and Filtering:** With JSON, one could store complex, nested data that can be easily parsed and queried. This means that QUIVR can support more sophisticated search and filtering capabilities, allowing users to retrieve exactly what they need, faster and with greater precision. 

4. **Future-Proofing:** As data structures evolve, JSON's flexibility ensures your application remains adaptable. Adding JSON support today sets the stage for easily accommodating future data formats and structures, keeping QUIVR ahead of the curve.

5. **Improved User Experience:** Users benefit from more accurate, contextually relevant results, and the ability to interact with data in a more intuitive way. JSON's structure supports this by enabling a more organized and efficient handling of complex datasets.

**Comment by remoteblue** [comment]
+1. Is there any temporary measure to digest JSON while this feature is not available?
