### ISSUE TITLE
[Feature]: Renaming "BRAIN" with "EXPERT"

### ISSUE THREAD

**Issue by atulgrover** [QuivrHQ/quivr#3011]
### The Feature

"add an expert" sounds better thatn "add a brain"

### Motivation, pitch

Renaming "Brain" to "Experts" in QUIVR would enhance both the user experience and the perceived value of the platform.

1. **User-Friendly Language**: "Expert" is a term that resonates more naturally with users. It conveys a sense of reliability and authority, making the process of adding documents feel more intuitive and aligned with real-world analogies. Users are more likely to understand and appreciate the concept of "adding an expert" rather than "adding a brain," which sounds abstract or confusing.

2. **Enhanced Perception**: The term "Expert" will add a layer of professionalism and sophistication to QUIVR. It suggests that the information being added is curated and authoritative, positioning your platform as a go-to resource for expert-level insights and knowledge.

3. **Contextual Relevance**: In many professional and educational settings, the word "Expert" carries weight and significance. By aligning QUIVR with this terminology, we can create a more relevant and meaningful user experience, especially for users seeking specialized information.

4. **Better Communication**: When users share or discuss QUIVR, referring to "Experts" instead of "Brains" is likely to facilitate clearer and more effective communication. It immediately conveys the idea of adding knowledge or resources from authoritative sources.

5. **Increased Engagement**: The more relatable and accessible the language of QUIVR, the more likely users are to engage with it. "Adding an Expert" sounds actionable and purposeful, encouraging users to actively contribute to and interact with QUIVR.

**Comment by Sid-80** [comment]
@atulgrover I am willing to work on this issue
