### ISSUE TITLE
[Bug]: the knowledge counter is stuck at 1000

### ISSUE THREAD

**Issue by atulgrover** [QuivrHQ/quivr#3137]
### What happened?

A bug happened!
![image](https://github.com/user-attachments/assets/b8a47523-36d3-4460-aef6-cc41f0ec6e88)
[Bug]: the knowledge counter is stuck at 1000

**Comment by StanGirard** [comment]
Hey Mate, <br><br>You can go to `backend/supabase/config.toml` and increase the max rows to 2000. Be careful it has some performance issues -> 

<img src="https://uploads.linear.app/51e2032d-a488-42cf-9483-a30479d3e2d0/71fba78b-1c26-45c5-bb42-1382c65b4e2f/99b3e4fa-575d-4448-865e-84c78928abd5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUxZTIwMzJkLWE0ODgtNDJjZi05NDgzLWEzMDQ3OWQzZTJkMC83MWZiYTc4Yi0xYzI2LTQ1YzUtYmI0Mi0xMzgyYzY1YjRlMmYvOTliM2U0ZmEtNTc1ZC00NDQ4LTg2NWUtODRjNzg5MjhhYmQ1IiwiaWF0IjoxNzI1MzU4OTI5LCJleHAiOjMzMjk1OTE4OTI5fQ.bJbAK__RVmvPM9u-bP5LNykVlVO64WRDz9GilHEtWco " alt="image.png" width="1024" height="327" />

Then simply `supabase stop && supabase start` and you'll be good to go
