### ISSUE TITLE
Enabling data ingestion pipelines

### ISSUE THREAD

**Issue by jacopo-chevallard** [QuivrHQ/quivr#3168]
For now, the ingestion of new data is managed in `backend/worker/quivr_worker/process/process_file.py` or in `backend/core/quivr_core/brain/brain.py` using the `get_processor_class` in `backend/core/quivr_core/processor/registry.py`. 

This approach prevents the construction and use of more complex ingestion pipelines, for instance based on LangGraph. 

We would need to restructure the code so that a Data Ingestion pipeline can be build and used by  `backend/core/quivr_core/brain/brain.py` or by  `backend/api/quivr_api/modules/upload/controller/upload_routes.py`

**Comment by AmineDiro** [comment]
`quivr-core`  basically uses the registry to find the processor that matches a file extension. 

The internal implementation of the processor could be **as complex or as we want.** As long as the processor implements ProcessorBase it can be added to the registry 👍🏼  The internal steps / parsing will all be internal to the processor and can use any external dependencies as we want.

**Comment by jacopo-chevallard** [comment]
Cool, I see, so for pdf files I can basically start from `backend/core/quivr_core/processor/implementations/megaparse_processor.py` and modify as I want
