### ISSUE TITLE
[Bug]: New install cannot log in over local network and frontend seems incomplete.

### ISSUE THREAD

**Issue by root-reindeer-flotilla** [QuivrHQ/quivr#3169]
### What happened?

I installed quivr on my local windows machine with docker desktop. I got everything to work yesterday after a few hours. I decided to move my install to my server so I can access it over my network. I'm using proxmox to which I installed a debian container that has docker installed on it. I set up everything mostly the same but I'm getting this very weird frontend bug. I try to enter admin@quivr.app admin and login and nothing happens at all. 

The supabase install works well, and even 10.10.10.101:5050/docs#/ works as I can visit them like normal.

Does anyone have any ideas?

![image](https://github.com/user-attachments/assets/28971da9-4b6f-4032-bf32-ea694efcda9b)

**Comment by aishock** [comment]
Hi, you mentioned that you once got everything worked on your local machine, do you mind sharing more details of what models you used (such as ChatGPT, Ollama) and how you add in the models to Quivr?
