### ISSUE TITLE
Should this work with the free version of OpenAI?

### ISSUE THREAD

**Issue by jpadfield** [QuivrHQ/quivr#44]
Hi,

Should one be able to test this system with the free version of OpenAI? 

I have managed to install all of the software but I received an error saying I had reached my OpenAI limit when trying to upload my first PDF. 

I am currently exploring the alternative Anthropic models as well.

Thanks

Joe

**Comment by StanGirard** [comment]
You need to put your credit card unfortunately :/ 

Or you can try the demo available https://try-quivr.streamlit.app

**Comment by jpadfield** [comment]
If I can get access to Anthropic models - is it possible to test a local system for free?

Thanks for the demo link but it keeps has given me an error relating to 

"File "/app/quivr/files.py", line 48, in file_already_exists
    file_sha1 = compute_sha1_from_content(file.getvalue())
                                          ^^^^^^^^^^^^^"

I tried two different files one small txt and one larger pdf.

**Comment by StanGirard** [comment]
The local version is free :) You can test it locally and you'll have more features. However you'll have to use your API keys
